{
  "hash": "6bbc70cd9f395e5b0a3d2ddc010a6c8e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"In-class Exercise 9\"\nauthor: \"Kock Si Min\"\ndate: October 28, 2024\ndate-modified: \"last-modified\"\ntoc: true\nexecute:\n  eval: true\n  echo: true\n  freeze: true\n  warning: false\n  message: false\n---\n\n\n# Modelling Geographical Accessibility\n\n-   Prof shared that for real-life cases, we cannot use fixed capacity and demand i.e. 100 used in hands-on exercise 9, instead we need to determine real figures\n\n## The Data\n\nFour datasets will be used:\n\n-   `MP14_SUBZONE_NO_SEA_PL`: URA Master Plan 2014 subzone boundary GIS data. This data set is downloaded from data.gov.sg.\n\n-   `hexagons`: A 250m radius hexagons GIS data. This data set was created by using [*st_make_grid()*](https://r-spatial.github.io/sf/reference/st_make_grid.html) of sf package. It is in ESRI shapefile format.\n\n-   `ELDERCARE`: GIS data showing location of eldercare service. [This data](https://data.gov.sg/dataset/eldercare-services) is downloaded from data.gov.sg. There are two versions. One in ESRI shapefile format. The other one in Google kml file format. For the purpose of this hands-on exercise, ESRI shapefile format is provided.\n\n-   `OD_Matrix`: a distance matrix in csv format. There are six fields in the data file. They are:\n\n    -   `origin_id`: the unique id values of the origin (i.e. `fid` of hexagon data set.),\n\n    -   `destination_id`: the unique id values of the destination (i.e. `fid` of `ELDERCARE` data set.),\n\n    -   `entry_cost`: the perpendicular distance between the origins and the nearest road),\n\n    -   `network_cost`: the actual network distance from the origin and destination,\n\n    -   `exit_cost`: the perpendicular distance between the destination and the nearest road), and\n\n    -   `total_cost`: the summation of `entry_cost`, `network_cost` and `exit_cost`.\n\nAll values of the cost-related fields are in metres.\n\n## Getting Started\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf,SpatialAcc,tidyverse,tmap,ggstatsplot, reshape2,rstantools)\n```\n:::\n\n\n## Geospatial Data Wrangling\n\n### Importing geospatial data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz <- st_read(dsn = \"data/geospatial\",\n                layer = \"MP14_SUBZONE_NO_SEA_PL\") %>%\n  st_transform(3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `MP14_SUBZONE_NO_SEA_PL' from data source \n  `C:\\mooseksm\\ISSS626-GAA\\In-class_Ex\\In-class_Ex09\\data\\geospatial' \n  using driver `ESRI Shapefile'\nSimple feature collection with 323 features and 15 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 2667.538 ymin: 15748.72 xmax: 56396.44 ymax: 50256.33\nProjected CRS: SVY21\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhexagons <- st_read(dsn = \"data/geospatial\",\n                layer = \"hexagons\") %>%\n  st_transform(3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `hexagons' from data source \n  `C:\\mooseksm\\ISSS626-GAA\\In-class_Ex\\In-class_Ex09\\data\\geospatial' \n  using driver `ESRI Shapefile'\nSimple feature collection with 3125 features and 6 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: 2667.538 ymin: 21506.33 xmax: 50010.26 ymax: 50256.33\nProjected CRS: SVY21 / Singapore TM\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\neldercare <- st_read(dsn = \"data/geospatial\",\n                layer = \"ELDERCARE\") %>%\n  st_transform(3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `ELDERCARE' from data source \n  `C:\\mooseksm\\ISSS626-GAA\\In-class_Ex\\In-class_Ex09\\data\\geospatial' \n  using driver `ESRI Shapefile'\nSimple feature collection with 120 features and 19 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 14481.92 ymin: 28218.43 xmax: 41665.14 ymax: 46804.9\nProjected CRS: SVY21 / Singapore TM\n```\n\n\n:::\n:::\n\n\n### Data cleaning and updating attribute fields of the geospatial data\n\n-   supply\n\n    -   artificially create a new column \"capacity\" to make it easy to calibrate the model\n\n    -   but in reality, need to collect real data i.e. survey, web crawling to collect actual capacity of eldercare centre\n\n    -   retain fid and ADDRESSPOS which represent id and address of eldercare\n\n\n::: {.cell}\n\n```{.r .cell-code}\neldercare <- eldercare %>%\n  select(fid,ADDRESSPOS) %>%\n  mutate(capacity = 100)\n```\n:::\n\n\n-   demand\n\n    -   artificially create a new column \"demand\" to make it easy to calibrate the model\n\n    -   but in reality, need to collect real data i.e. crawl from hdb website the number of floors then multiply by constant unit to estimate number of elderly folks\n\n    -   retain unique id aka fid\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhexagons <- hexagons %>%\n  select(fid) %>%\n  mutate(demand = 100)\n```\n:::\n\n\n## Aspatial Data Handling and Wrangling\n\n### Importing Distance Matrix\n\n-   for info, Prof used [r5r](https://cran.r-project.org/web/packages/r5r/vignettes/r5r.html) to create ODMatrix; is a java library that calculate shorter distance from road network i.e. OpenStreetMap\n\n-   note that ODMatrix is in the structure of long and thin - this is how its returned from r5r:\n\n    -   total cost is summation of entry, network and exit costs\n\n    -   entry cost: perpendicular distance from origin point to nearest road i.e. walk/bus to mrt distance\n\n    -   exit cost: perpendicular distance from destination point to nearest road\n\n\n::: {.cell}\n\n```{.r .cell-code}\nODMatrix <- read_csv(\"data/aspatial/OD_Matrix.csv\", skip = 0)\n```\n:::\n\n\n### Tidying distance matrix\n\n-   **rows represent origins** i.e. aka **the from field** and the **columns represent destinations** i.e. aka the to field\n-   code chunk below uses *spread()* of **tidyr** package to **transform the ODMatrix from a thin format into a fat format:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndistmat <- ODMatrix %>%\n  select(origin_id,destination_id,total_cost) %>%\n  pivot_wider(names_from= destination_id,\n              values_from = total_cost) %>%\n  select(c(-c('origin_id')))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndistmat_km <- as.matrix(distmat/1000)\n```\n:::\n\n\n-   note that distmat_km is 3125 observations of 120 variables - 3125 match with hexagons 3125 observations of 3 variables (demand), 120 match with eldercare 120 observations of 4 variables (supply)\n\n-   Prof shared that should use pivot_longer()\n\n## Modelling and Visualising Accessibility using Hansen Method\n\n### Computing Hansen's accessibility\n\n\n::: {.cell}\n\n```{.r .cell-code}\nacc_Hansen <- data.frame(ac(hexagons$demand,\n                            eldercare$capacity,\n                            distmat_km,\n                            d0 = 50,\n                            power = 2,\n                            family = \"Hansen\"))\n\ncolnames(acc_Hansen) <- \"accHansen\"\nacc_Hansen <- as_tibble(acc_Hansen)\nhexagon_Hansen <- bind_cols(hexagons,acc_Hansen)\n```\n:::\n\n\n### Visualising Hansen's accessibility\n\n#### Extracting map extend\n\nWe will extract the extend of hexagons simple feature data frame by using *st_bbox()* of sf package:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmapex <- st_bbox(hexagons)\nmapex\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     xmin      ymin      xmax      ymax \n 2667.538 21506.334 50010.260 50256.334 \n```\n\n\n:::\n:::\n\n\nThe code chunk below uses a collection of mapping functions of the **tmap** package to create a high cartographic quality map to indicate the accessibility to eldercare centres in Singapore:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode('plot')\ntm_shape(hexagon_Hansen,\n         bbox = mapex) +\n  tm_fill(col = \"accHansen\",\n          n = 10,\n          style = \"quantile\",\n          border.col = \"black\",\n          border.lwd = 1)+\n  tm_shape(eldercare) +\n  tm_symbols(size = 0.1, col = \"skyblue\") +\n  tm_layout(main.title = \"Accessibility to eldercare: Hansen method\",\n            main.title.position = \"center\",\n            main.title.size = 2,\n            legend.outside = FALSE,\n            legend.height = 0.28,\n            legend.width = 3.0,\n            legend.format = list(digits = 6),\n            legend.position = c(\"right\",\"top\"),\n            frame = TRUE) +\n  tm_compass(type = \"8star\", size = 2) +\n  tm_scale_bar(width = 0.15)+\n  tm_grid(lwd = 0.1, alpha = 0.5)\n```\n\n::: {.cell-output-display}\n![](In-class_Ex09_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\n## Questions to raise\n\n-   why do i need to indicate bbox = mapex when the geometry in hexagon_Hansen is based on the hexagons polygon geometry?\n    -   Prof wants to make sure extend does not change, ensure that every plot will have the same map extend\n:::\n\n### Statistical graphic visualisation\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhexagon_Hansen <- st_join(hexagon_Hansen, mpsz,\n                          join = st_intersects)\n```\n:::\n\n\nWe use ggplot to plot the distribution via boxplot:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(hexagon_Hansen,\n       aes(y=log(accHansen),\n           x= REGION_N))+\n  geom_boxplot()+\n  geom_point(stat = \"summary\",\n             fun.y = \"mean\",\n             color = \"red\",\n             size = 2)\n```\n\n::: {.cell-output-display}\n![](In-class_Ex09_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nWe also utilise ggbetweenstats:\n\n-   combines EDA with CDA and showcases it in one framework\n\n-   type = \"p\" indicate parametric test which compares mean value, \"np\" would mean non-parametric test which compares the median, \"robust\" method would trim outliers, \"bayes\" method means it create multiple permutations before presenting cut-off line\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggbetweenstats(data = hexagon_Hansen,\n               x= REGION_N,\n               y = accHansen,\n               type = \"p\")\n```\n\n::: {.cell-output-display}\n![](In-class_Ex09_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n## \n",
    "supporting": [
      "In-class_Ex09_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}