project:
  type: website

website:
  title: "ISSS626-GAA"
  navbar:
    left:
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1A
            href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01A.html
          - text: Hands-on Exercise 1B
            href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01B.html
          - text: Hands-on Exercise 2A
            href: Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02A.html
          - text: Hands-on Exercise 2B
            href: Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02B.html
          - text: Hands-on Exercise 3
            href: Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html
          - text: Hands-on Exercise 4
            href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html
          - text: Hands-on Exercise 5A
            href: Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05A.html
          - text: Hands-on Exercise 5B
            href: Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05B.html
          - text: Hands-on Exercise 6
            href: Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html
      - text: In-class Exercises
        menu: 
          - text: In-class Exercise 1
            href: In-class_Ex/In-class_Ex01/In-class_Ex01.html
          - text: In-class Exercise 2
            href: In-class_Ex/In-class_Ex02/In-class_Ex02.html
          - text: In-class Exercise 3
            href: In-class_Ex/In-class_Ex03/In-class_Ex03.html
          - text: In-class Exercise 4
            href: In-class_Ex/In-class_Ex04/In-class_Ex04.html
          - text: In-class Exercise 5
            href: In-class_Ex/In-class_Ex05/In-class_Ex05.html
      - text: Take-home Exercises
        menu: 
          - text: Take-Home Exercise 1A
            href: Take-home_Ex/Take-home_Ex01/Take-home_Ex01A.html
          - text: Take-Home Exercise 1B
            href: Take-home_Ex/Take-home_Ex01/Take-home_Ex01B.html
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-location: left

editor: visual

