{
  "hash": "1e526f0b5806ae3edf2629e50a738085",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home Exercise 1B\"\nauthor: \"Kock Si Min\"\ndate: September 2, 2024\ndate-modified: \"last-modified\"\ntoc: true\nexecute:\n  eval: true\n  echo: true\n  freeze: true\n  warning: false\n  message: false\n---\n\n\n# Take-Home Exercise 1: Geospatial Analytics for Public Good (Part 1B)\n\n#### Loading the necessary R packages and data created in [Part 1A](https://isss626-ksm.netlify.app/take-home_ex/take-home_ex01/take-home_ex01a)\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\npacman::p_load(sf,spatstat,raster,maptools,tmap,tidyverse,spNetwork,DT,forcats,ggthemes,plotly,RColorBrewer)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# loading datasets for analysis\n#refer to Part 1A for earlier steps on data wrangling\nroadacc <- read_rds(\"data/rds/roadacc.rds\")\nroadsbkk <- read_rds(\"data/rds/roadsbkk.rds\")\nprovincedata32647 <- read_rds(\"data/rds/provincedata32647.rds\")\nroadacc_month_bkk <- read_rds(\"data/rds/roadacc_month_bkk.rds\")\nroadacc_month_sp <- read_rds(\"data/rds/roadacc_month_sp.rds\")\nroadacc_month_n <- read_rds(\"data/rds/roadacc_month_n.rds\")\nroadacc_month_pt <- read_rds(\"data/rds/roadacc_month_pt.rds\")\nroadacc_month_np <- read_rds(\"data/rds/roadacc_month_np.rds\")\nroadacc_month_ss <- read_rds(\"data/rds/roadacc_month_ss.rds\")\n```\n:::\n\n\n## 7. Spatial Point Pattern Analysis (SPPA)\n\nWe will conduct a Spatial Point Pattern Analysis (SPPA) to evaluate the distribution of road accidents within the Bangkok Metropolitan Region (BMR).\n\nThe specific questions we would like to answer are as follows:\n\n-   are the road accidents in BMR randomly distributed throughout the region?\n\n-   if no, then where are the locations with higher concentration of road accidents?\n\nSpecifically, we will be carrying out the following SPPA methods:\n\n-   First-order SPPA\n\n-   Spatial analysis of road traffic accidents using Network SPPA methods.\n\n-   Spatio-temporal analysis of road accidents using Temporal Network SPPA methods.\n\n## 7.1 Data Wrangling for SPPA\n\n### 7.1.1 Converting data to ppp format for Spatial Point Pattern Analysis\n\nBefore we carry out spatial point pattern analysis, we need to convert the data from sf format to ppp format:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroadacc_ppp <- as.ppp(roadacc)\nroadacc_ppp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern: 12985 points\nmarks are numeric, of storage type  'double'\nwindow: rectangle = [591277.5, 710166.1] x [1486845.7, 1576520.5] units\n```\n\n\n:::\n:::\n\n\nThe code chunk below plots *roadacc_ppp* for visualisation:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(roadacc_ppp)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01B_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nWe take a quick look at the summary statistics of the *roadacc_ppp* object using the code chunk below:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(roadacc_ppp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern:  12985 points\nAverage intensity 1.217956e-06 points per square unit\n\nCoordinates are given to 10 decimal places\n\nmarks are numeric, of type 'double'\nSummary:\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 571882 3788970 3833867 4314374 6092695 7570954 \n\nWindow: rectangle = [591277.5, 710166.1] x [1486845.7, 1576520.5] units\n                    (118900 x 89670 units)\nWindow area = 10661300000 square units\n```\n\n\n:::\n:::\n\n\n### 7.1.2 Checking for duplicate points\n\nIn SPPA, a significant issue is the presence of duplicates as the statistical methodology used for spatial point patterns processes is based largely on the assumption that process are simple i.e. that the points cannot be coincident. We check for duplication in a *ppp* object via the code chunk below:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nany(duplicated(roadacc_ppp))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n:::\n\n\nThe data does not have any duplicated points.\n\n### 7.1.3 Creating an *owin* object\n\nWhen analysing spatial point patterns, it is a good practice to confine the analysis within a geographical area like Singapore boundary. In **spatstat**, an object called *owin* is specially designed to represent this polygonal region. The code chunk below is used to covert *provincedata32647* SpatialPolygon object into owin object of **spatstat**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprovinceowin <- as.owin(provincedata32647)\n```\n:::\n\n\nThe ouput object can be displayed by using *plot()* function\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(provinceowin)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01B_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(provinceowin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWindow: polygonal boundary\nsingle connected closed polygon with 13779 vertices\nenclosing rectangle: [587893.5, 712440.5] x [1484413.7, 1579076.3] units\n                     (124500 x 94660 units)\nWindow area = 7668990000 square units\nFraction of frame area: 0.65\n```\n\n\n:::\n:::\n\n\n### 7.1.4 Combining point events object and owin object\n\nWe extract road accident events that are located within the BMR by using the code chunk below:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroadacc_owin_ppp = roadacc_ppp[provinceowin]\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(roadacc_owin_ppp)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01B_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(roadacc_owin_ppp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern:  12985 points\nAverage intensity 1.693182e-06 points per square unit\n\nCoordinates are given to 10 decimal places\n\nmarks are numeric, of type 'double'\nSummary:\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 571882 3788970 3833867 4314374 6092695 7570954 \n\nWindow: polygonal boundary\nsingle connected closed polygon with 13779 vertices\nenclosing rectangle: [587893.5, 712440.5] x [1484413.7, 1579076.3] units\n                     (124500 x 94660 units)\nWindow area = 7668990000 square units\nFraction of frame area: 0.65\n```\n\n\n:::\n:::\n\n\n## 7.2 First-order SPPA\n\nThe first-order SPPA will study how the intensity of road accidents vary across the BMR i.e. identify whether road accidents are more concentrated in areas due to underlying properties of the spatial environment.\n\nFor first-order SPPA, we will:\n\n-   derive the **kernel density estimation (KDE)** layer for visualising and exploring the intensity of point processes,\n\n-   perform **Confirmatory SPPA** using **Nearest Neighbour** statistics to determine if the road accidents are randomly distributed or influenced by underlying properties of the spatial environment.\n\n### 7.2.1 Kernel Density Estimation (KDE)\n\nWe will proceed to compute the KDE of road accidents in the BMR. However, before we do so, we convert the unit of measurement to kilometer as the default unit of measurement of EPSG: 32647 is in metres, which would make the values hard to comprehend:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroadacc_owin_ppp.km <- rescale.ppp(roadacc_owin_ppp,1000,\"km\")\n```\n:::\n\n\n### 7.2.1.1 Computing KDE using automatic bandwidth selection\n\nWe will derive KDE using *bw.diggle()* of spatstat as it is an automatic bandwidth selection method and does not require a fixed bandwidth to be defined.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_roadacc_bw <- density(roadacc_owin_ppp.km,\n                          sigma = bw.diggle,\n                          edge = TRUE,\n                          kernel = \"gaussian\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(kde_roadacc_bw)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01B_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nWe can retrieve the bandwidth used to compute the KDE layer with the code chunk below:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw <- bw.diggle(roadacc_owin_ppp)\nbw\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   sigma \n13.41598 \n```\n\n\n:::\n:::\n\n\n### 8.1.1 Converting KDE output into grid object\n\nWe convert the KDE output for mapping purposes:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngridded_kde_roadacc_bw <- as.SpatialGridDataFrame.im(kde_roadacc_bw)\nspplot(gridded_kde_roadacc_bw)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01B_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n### 8.1.2 Converting gridded output into raster\n\nNext, we will convert the gridded KDE object into a RasterLayer object using *raster()* of **raster package**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_roadacc_bw_raster <- raster(kde_roadacc_bw)\n```\n:::\n\n\nWe view the properties of *kde_roadacc_bw_raster* RasterLayer:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_roadacc_bw_raster\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass      : RasterLayer \ndimensions : 128, 128, 16384  (nrow, ncol, ncell)\nresolution : 0.973023, 0.7395512  (x, y)\nextent     : 587.8935, 712.4405, 1484.414, 1579.076  (xmin, xmax, ymin, ymax)\ncrs        : NA \nsource     : memory\nnames      : layer \nvalues     : -4.811931e-14, 233.4629  (min, max)\n```\n\n\n:::\n:::\n\n\nNote that the CRS property is NA.\n\n### 8.1.3 Assigning projection system\n\nWe hence assign CRS information to the *kde_roadacc_bw_raster* RasterLayer:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprojection(kde_roadacc_bw_raster) <- CRS(\"+init=EPSG:32647\")\n\nkde_roadacc_bw_raster\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass      : RasterLayer \ndimensions : 128, 128, 16384  (nrow, ncol, ncell)\nresolution : 0.973023, 0.7395512  (x, y)\nextent     : 587.8935, 712.4405, 1484.414, 1579.076  (xmin, xmax, ymin, ymax)\ncrs        : +proj=utm +zone=47 +datum=WGS84 +units=m +no_defs \nsource     : memory\nnames      : layer \nvalues     : -4.811931e-14, 233.4629  (min, max)\n```\n\n\n:::\n:::\n\n\nThe CRS property is now completed.\n\n### 8.1.4 Visualising the output in tmap\n\nWe will display the raster in cartographic quality map using **tmap package**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode('plot')\ntm_shape(kde_roadacc_bw_raster)+   \n  tm_raster(\"layer\",palette = \"viridis\")+   \n  tm_layout(legend.outside = TRUE,             \n            legend.outside.position = \"right\",             \n            legend.position = c(\"right\",\"bottom\"),             \n            main.title = \"Distribution of road accidents (bw.diggle)\", \n            main.title.size = 0.8,             \n            frame = FALSE)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01B_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\nFrom the plot above, we note that road accidents occur more intensely along the road lines in Bangkok and Samut Prakan. To better understand how the intensity of road accidents occur across the BMR, we will extract the six provinces as different study areas for analysis and comparison in the next section.\n\n### 8.2 Comparing Spatial Point Patterns using KDE\n\n### 8.2.1 Extracting study areas\n\nThe code chunk will be used to extract the different provinces as different study areas:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbkk <- provincedata32647 %>%\n  filter(ADM1_EN == \"Bangkok\")\nnp <- provincedata32647 %>% \n  filter(ADM1_EN == \"Nakhon Pathom\") \nn <- provincedata32647 %>%   \n  filter(ADM1_EN == \"Nonthaburi\") \npt <- provincedata32647 %>%   \n  filter(ADM1_EN == \"Pathum Thani\") \nsp <- provincedata32647 %>%   \n  filter(ADM1_EN == \"Samut Prakan\") \nss <- provincedata32647 %>%   \n  filter(ADM1_EN == \"Samut Sakhon\")\n```\n:::\n\n\n### 8.2.2 Creating owin object for each study area\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbkk_owin = as.owin(bkk)\nnp_owin = as.owin(np) \nn_owin = as.owin(n) \npt_owin = as.owin(pt) \nsp_owin = as.owin(sp) \nss_owin = as.owin(ss)\n```\n:::\n\n\n### 8.2.3 Combining road accident points and study area\n\nBy using the code chunk below, we are able to extract road accidents that is within the specific province to carry out our analysis later on.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroadacc_bkk_ppp = roadacc_ppp[bkk_owin]\nroadacc_np_ppp = roadacc_ppp[np_owin]\nroadacc_n_ppp = roadacc_ppp[n_owin]\nroadacc_pt_ppp = roadacc_ppp[pt_owin]\nroadacc_sp_ppp = roadacc_ppp[sp_owin]\nroadacc_ss_ppp = roadacc_ppp[ss_owin]\n```\n:::\n\n\nNext, *rescale.ppp()* function is used to transform the unit of measurement from metres to kilometres as EPSG: 32647 is in metres which would produce density values that are too small to comprehend.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroadacc_bkk_ppp.km = rescale.ppp(roadacc_bkk_ppp,1000,\"km\")\nroadacc_np_ppp.km = rescale.ppp(roadacc_np_ppp,1000,\"km\")\nroadacc_n_ppp.km = rescale.ppp(roadacc_n_ppp,1000,\"km\")\nroadacc_pt_ppp.km = rescale.ppp(roadacc_pt_ppp,1000,\"km\")\nroadacc_sp_ppp.km = rescale.ppp(roadacc_sp_ppp,1000,\"km\")\nroadacc_ss_ppp.km = rescale.ppp(roadacc_ss_ppp,1000,\"km\")\n```\n:::\n\n\nWe save and load these files to minimise re-running the codes above:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nwrite_rds(roadacc_bkk_ppp.km,\"data/rds/roadacc_bkk_ppp.km.rds\")\nwrite_rds(roadacc_np_ppp.km,\"data/rds/roadacc_np_ppp.km.rds\")\nwrite_rds(roadacc_n_ppp.km,\"data/rds/roadacc_n_ppp.km.rds\")\nwrite_rds(roadacc_pt_ppp.km,\"data/rds/roadacc_pt_ppp.km.rds\")\nwrite_rds(roadacc_sp_ppp.km,\"data/rds/roadacc_sp_ppp.km.rds\")\nwrite_rds(roadacc_ss_ppp.km,\"data/rds/roadacc_ss_ppp.km.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nroadacc_bkk_ppp.km <- read_rds(\"data/rds/roadacc_bkk_ppp.km.rds\")\nroadacc_np_ppp.km <- read_rds(\"data/rds/roadacc_np_ppp.km.rds\")\nroadacc_n_ppp.km <- read_rds(\"data/rds/roadacc_n_ppp.km.rds\")\nroadacc_pt_ppp.km <- read_rds(\"data/rds/roadacc_pt_ppp.km.rds\")\nroadacc_sp_ppp.km <- read_rds(\"data/rds/roadacc_sp_ppp.km.rds\")\nroadacc_ss_ppp.km <- read_rds(\"data/rds/roadacc_ss_ppp.km.rds\")\n```\n:::\n\n\nWe then plot the 6 provinces and the locations of the road accidents:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(2,3))\nplot(roadacc_bkk_ppp.km,main=\"Bangkok\")\nplot(roadacc_np_ppp.km,main=\"Nakhon Pathom\")\nplot(roadacc_n_ppp.km,main=\"Nonthaburi\") \nplot(roadacc_pt_ppp.km,main=\"Pathum Thani\")\nplot(roadacc_sp_ppp.km,main=\"Samut Prakan\")\nplot(roadacc_ss_ppp.km,main=\"Samut Sakhon\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01B_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\n### 8.2.4 Computing KDE for each study area\n\nWe will also derive KDE using *bw.diggle()* of spatstat for all six provinces:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_bkk_bw <- density(roadacc_bkk_ppp.km,\n                      sigma = bw.diggle,\n                      edge = TRUE,\n                      kernel = \"gaussian\")\nkde_np_bw <- density(roadacc_np_ppp.km,\n                     sigma = bw.diggle,\n                     edge = TRUE,\n                     kernel = \"gaussian\")\nkde_n_bw <- density(roadacc_n_ppp.km,\n                    sigma = bw.diggle,\n                    edge = TRUE,\n                    kernel = \"gaussian\")\nkde_pt_bw <- density(roadacc_pt_ppp.km,\n                     sigma = bw.diggle,\n                     edge = TRUE,\n                     kernel = \"gaussian\")\nkde_sp_bw <- density(roadacc_sp_ppp.km,\n                     sigma = bw.diggle,\n                     edge = TRUE,\n                     kernel = \"gaussian\")\nkde_ss_bw <- density(roadacc_ss_ppp.km,\n                     sigma = bw.diggle,\n                     edge = TRUE,\n                     kernel = \"gaussian\")\n```\n:::\n\n\nWe also save and load these as new rds files to minimise re-running the code above:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nwrite_rds(kde_bkk_bw,\"data/rds/kde_bkk_bw.rds\")\nwrite_rds(kde_np_bw,\"data/rds/kde_np_bw.rds\")\nwrite_rds(kde_n_bw,\"data/rds/kde_n_bw.rds\")\nwrite_rds(kde_pt_bw,\"data/rds/kde_pt_bw.rds\")\nwrite_rds(kde_sp_bw,\"data/rds/kde_sp_bw.rds\")\nwrite_rds(kde_ss_bw,\"data/rds/kde_ss_bw.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_bkk_bw <- read_rds(\"data/rds/kde_bkk_bw.rds\")\nkde_np_bw <- read_rds(\"data/rds/kde_np_bw.rds\")\nkde_n_bw <- read_rds(\"data/rds/kde_n_bw.rds\")\nkde_pt_bw <- read_rds(\"data/rds/kde_pt_bw.rds\")\nkde_sp_bw <- read_rds(\"data/rds/kde_sp_bw.rds\")\nkde_ss_bw <- read_rds(\"data/rds/kde_ss_bw.rds\")\n```\n:::\n\n\nNext, we will convert the KDE object into a RasterLayer object using *raster()* of **raster package** and assign the CRS of EPSG 32647:\n\n::: panel-tabset\n## Bangkok\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_bkk_bw_raster <- raster(kde_bkk_bw)\nprojection(kde_bkk_bw_raster) <- CRS(\"+init=EPSG:32647\")  \nkde_bkk_bw_raster\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass      : RasterLayer \ndimensions : 128, 128, 16384  (nrow, ncol, ncell)\nresolution : 0.5157047, 0.4002078  (x, y)\nextent     : 643.5344, 709.5446, 1492.136, 1543.363  (xmin, xmax, ymin, ymax)\ncrs        : +proj=utm +zone=47 +datum=WGS84 +units=m +no_defs \nsource     : memory\nnames      : layer \nvalues     : -1.081234e-13, 523.2836  (min, max)\n```\n\n\n:::\n:::\n\n\n## Nakhon Pathom\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_np_bw_raster <- raster(kde_np_bw)\nprojection(kde_np_bw_raster) <- CRS(\"+init=EPSG:32647\")  \nkde_np_bw_raster\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass      : RasterLayer \ndimensions : 128, 128, 16384  (nrow, ncol, ncell)\nresolution : 0.4431169, 0.4584598  (x, y)\nextent     : 587.8935, 644.6125, 1509.208, 1567.891  (xmin, xmax, ymin, ymax)\ncrs        : +proj=utm +zone=47 +datum=WGS84 +units=m +no_defs \nsource     : memory\nnames      : layer \nvalues     : -9.825693e-15, 59.06928  (min, max)\n```\n\n\n:::\n:::\n\n\n## Nonthaburi\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_n_bw_raster <- raster(kde_n_bw)\nprojection(kde_n_bw_raster) <- CRS(\"+init=EPSG:32647\")  \nkde_n_bw_raster\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass      : RasterLayer \ndimensions : 128, 128, 16384  (nrow, ncol, ncell)\nresolution : 0.2577626, 0.3028132  (x, y)\nextent     : 636.3416, 669.3352, 1524.865, 1563.625  (xmin, xmax, ymin, ymax)\ncrs        : +proj=utm +zone=47 +datum=WGS84 +units=m +no_defs \nsource     : memory\nnames      : layer \nvalues     : -2.80486e-14, 179.3522  (min, max)\n```\n\n\n:::\n:::\n\n\n## Pathum Thani\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_pt_bw_raster <- raster(kde_pt_bw)\nprojection(kde_pt_bw_raster) <- CRS(\"+init=EPSG:32647\")  \nkde_pt_bw_raster\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass      : RasterLayer \ndimensions : 128, 128, 16384  (nrow, ncol, ncell)\nresolution : 0.5218025, 0.3122371  (x, y)\nextent     : 643.7786, 710.5693, 1539.11, 1579.076  (xmin, xmax, ymin, ymax)\ncrs        : +proj=utm +zone=47 +datum=WGS84 +units=m +no_defs \nsource     : memory\nnames      : layer \nvalues     : -5.136259e-14, 233.2346  (min, max)\n```\n\n\n:::\n:::\n\n\n## Samut Prakan\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_sp_bw_raster <- raster(kde_sp_bw)\nprojection(kde_sp_bw_raster) <- CRS(\"+init=EPSG:32647\")  \nkde_sp_bw_raster\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass      : RasterLayer \ndimensions : 128, 128, 16384  (nrow, ncol, ncell)\nresolution : 0.4386052, 0.2064404  (x, y)\nextent     : 656.299, 712.4405, 1490.796, 1517.22  (xmin, xmax, ymin, ymax)\ncrs        : +proj=utm +zone=47 +datum=WGS84 +units=m +no_defs \nsource     : memory\nnames      : layer \nvalues     : -1.479576e-13, 739.9567  (min, max)\n```\n\n\n:::\n:::\n\n\n## Samut Sakhon\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkde_ss_bw_raster <- raster(kde_ss_bw)\nprojection(kde_ss_bw_raster) <- CRS(\"+init=EPSG:32647\")\nkde_ss_bw_raster\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass      : RasterLayer \ndimensions : 128, 128, 16384  (nrow, ncol, ncell)\nresolution : 0.332527, 0.2598575  (x, y)\nextent     : 611.1044, 653.6678, 1484.414, 1517.676  (xmin, xmax, ymin, ymax)\ncrs        : +proj=utm +zone=47 +datum=WGS84 +units=m +no_defs \nsource     : memory\nnames      : layer \nvalues     : -5.709496e-14, 324.038  (min, max)\n```\n\n\n:::\n:::\n\n:::\n\n### 8.1.4 Visualising the output in tmap\n\nWe will display the raster in cartographic quality map using **tmap package**:\n\n::: panel-tabset\n## Bangkok\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(kde_bkk_bw_raster)+\n  tm_raster(\"layer\",palette = \"viridis\")+\n  tm_layout(legend.outside = TRUE,\n            legend.outside.position = \"right\",\n            legend.position = c(\"right\",\"bottom\"),\n            main.title = \"Distribution of road accidents in Bangkok\",\n            main.title.size = 0.8,\n            frame = FALSE)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01B_files/figure-html/unnamed-chunk-39-1.png){width=672}\n:::\n:::\n\n\n## Nakhon Pathom\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(kde_np_bw_raster)+\n  tm_raster(\"layer\",palette = \"viridis\")+\n  tm_layout(legend.outside = TRUE,\n            legend.outside.position = \"right\",\n            legend.position = c(\"right\",\"bottom\"),\n            main.title = \"Distribution of road accidents in Nakhon Pathom\",\n            main.title.size = 0.8,\n            frame = FALSE)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01B_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\n\n## Nonthaburi\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(kde_n_bw_raster)+\n  tm_raster(\"layer\",palette = \"viridis\")+\n  tm_layout(legend.outside = TRUE,\n            legend.outside.position = \"right\",\n            legend.position = c(\"right\",\"bottom\"),\n            main.title = \"Distribution of road accidents in Nonthaburi\",\n            main.title.size = 0.8,\n            frame = FALSE)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01B_files/figure-html/unnamed-chunk-41-1.png){width=672}\n:::\n:::\n\n\n## Pathum Thani\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(kde_pt_bw_raster)+\n  tm_raster(\"layer\",palette = \"viridis\")+\n  tm_layout(legend.outside = TRUE,\n            legend.outside.position = \"right\",\n            legend.position = c(\"right\",\"bottom\"),\n            main.title = \"Distribution of road accidents in Pathum Thani\",\n            main.title.size = 0.8,\n            frame = FALSE)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01B_files/figure-html/unnamed-chunk-42-1.png){width=672}\n:::\n:::\n\n\n## Samut Prakan\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(kde_sp_bw_raster)+\n  tm_raster(\"layer\",palette = \"viridis\")+\n  tm_layout(legend.outside = TRUE,\n            legend.outside.position = \"right\",\n            legend.position = c(\"right\",\"bottom\"),\n            main.title = \"Distribution of road accidents in Samut Prakan\",\n            main.title.size = 0.8,\n            frame = FALSE)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01B_files/figure-html/unnamed-chunk-43-1.png){width=672}\n:::\n:::\n\n\n## Samut Sakhon\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(kde_ss_bw_raster)+\n  tm_raster(\"layer\",palette = \"viridis\")+\n  tm_layout(legend.outside = TRUE,\n            legend.outside.position = \"right\",\n            legend.position = c(\"right\",\"bottom\"),\n            main.title = \"Distribution of road accidents in Samut Sakhon\",\n            main.title.size = 0.8,\n            frame = FALSE)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01B_files/figure-html/unnamed-chunk-44-1.png){width=672}\n:::\n:::\n\n:::\n\nFrom the plots above, we note the maximum KDE for each province (in descending order) and details for each province as follows:\n\n-   [Samut Prakan]{.underline} - up to 600 to 800. Most of the road accidents optically seem to occur at 3 segments.\n\n-   [Bangkok]{.underline} - up to 500 to 600. Most of the road accidents optically seem to occur at major road lines.\n\n-   [Samut Sakhon]{.underline}: Max density up to 300 to 350. Most of the road accidents seem to occur along the same major road.\n\n-   [Pathum Thani]{.underline} - up to 200 to 250. Most of the road accidents seem to occur along the same major road.\n\n-   [Nonthaburi]{.underline} - up to 150 to 200. Most of the road accidents optically seem to be scattered.\n\n-   [Nakhon Pathom]{.underline} - up to 50 to 60. Most of the road accidents optically seem to be scattered.\n\nFurther comments are as follows:\n\n-   Notably, while Bangkok is a known tourist destination/major urban hub, it ranks second to Samut Prakan in terms of road accident density.\n-   Road accidents seem more scattered in Nonthaburi and Nakhon Pathom which suggest that there could be more complex road systems in these areas where accidents could occur at various points.\n\n## 9. Nearest Neighbour Analysis\n\nAfter running KDE which shows the density of road accidents over the BMR, we will perform the Clark-Evans test of aggregation to statistically validate the degree of spatial clustering or dispersion of the road accident points by comparing the observed mean nearest neighbor distance with the expected average distance between neighbours in a hypothetical random distribution.\n\nThe test hypotheses are:\n\nH0: The distribution of road accidents is randomly distributed.\n\nH1: The distribution of road accidents is not randomly distributed.\n\nThe 95% confidence interval will be used.\n\n### 9.1 Testing spatial point patterns using Clark and Evans Test\n\n### 9.1.1 Nearest Neighbour Analysis for overall data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclarkevans.test(roadacc_owin_ppp.km,\n                correction = \"none\",\n                clipregion = \"province_owin\",\n                alternative = c(\"clustered\"),\n                nsim = 999)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tClark-Evans test\n\tNo edge correction\n\tZ-test\n\ndata:  roadacc_owin_ppp.km\nR = 0.19092, p-value < 2.2e-16\nalternative hypothesis: clustered (R < 1)\n```\n\n\n:::\n:::\n\n\n-   Since p-value is less than 0.05, **there is sufficient evidence to reject the null hypothesis H0** that the distribution of road accidents is randomly distributed.\n\n-   This is further supported by the R value of 0.19092. As this R value is less than 1, it indicates that **the pattern exhibits clustering and that the road accidents tend to occur close to one another and not in a dispersed/regular manner.**\n\n### 9.1.2 Nearest Neighbour Analysis for each province\n\n::: panel-tabset\n## Bangkok\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclarkevans.test(roadacc_bkk_ppp.km,\n                correction=\"none\",\n                clipregion=NULL,\n                alternative=c(\"two.sided\"),\n                nsim=999)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tClark-Evans test\n\tNo edge correction\n\tZ-test\n\ndata:  roadacc_bkk_ppp.km\nR = 0.12057, p-value < 2.2e-16\nalternative hypothesis: two-sided\n```\n\n\n:::\n:::\n\n\n## Nakhon Pathom\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclarkevans.test(roadacc_np_ppp.km,\n                correction=\"none\",\n                clipregion=NULL,\n                alternative=c(\"two.sided\"),\n                nsim=999)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tClark-Evans test\n\tNo edge correction\n\tZ-test\n\ndata:  roadacc_np_ppp.km\nR = 0.28949, p-value < 2.2e-16\nalternative hypothesis: two-sided\n```\n\n\n:::\n:::\n\n\n## Nonthaburi\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclarkevans.test(roadacc_n_ppp.km,\n                correction=\"none\",\n                clipregion=NULL,\n                alternative=c(\"two.sided\"),\n                nsim=999)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tClark-Evans test\n\tNo edge correction\n\tZ-test\n\ndata:  roadacc_n_ppp.km\nR = 0.38919, p-value < 2.2e-16\nalternative hypothesis: two-sided\n```\n\n\n:::\n:::\n\n\n## Pathum Thani\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclarkevans.test(roadacc_pt_ppp.km,\n                correction=\"none\",\n                clipregion=NULL,\n                alternative=c(\"two.sided\"),\n                nsim=999)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tClark-Evans test\n\tNo edge correction\n\tZ-test\n\ndata:  roadacc_pt_ppp.km\nR = 0.24798, p-value < 2.2e-16\nalternative hypothesis: two-sided\n```\n\n\n:::\n:::\n\n\n## Samut Prakan\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclarkevans.test(roadacc_sp_ppp.km,\n                correction=\"none\",\n                clipregion=NULL,\n                alternative=c(\"two.sided\"),\n                nsim=999)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tClark-Evans test\n\tNo edge correction\n\tZ-test\n\ndata:  roadacc_sp_ppp.km\nR = 0.14367, p-value < 2.2e-16\nalternative hypothesis: two-sided\n```\n\n\n:::\n:::\n\n\n## Samut Sakhon\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclarkevans.test(roadacc_ss_ppp.km,\n                correction=\"none\",\n                clipregion=NULL,\n                alternative=c(\"two.sided\"),\n                nsim=999)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tClark-Evans test\n\tNo edge correction\n\tZ-test\n\ndata:  roadacc_ss_ppp.km\nR = 0.23989, p-value < 2.2e-16\nalternative hypothesis: two-sided\n```\n\n\n:::\n:::\n\n:::\n\nBased on the results above, for which all R values are less than 1 and all p-values are less than 0.05, we **reject the null hypothesis** at 95% confidence interval. **There is sufficient evidence to indicate that the distribution of road accidents in all provinces is not randomly distributed and instead exhibit clustering.**\n\n## 10. Network Constrained SPPA\n\nNetwork constrained SPPA (NetSPPA) is a collection of SAPPA methods specially developed for analysing spatial point events that occur on or alongside a network. In this case, it can be used for the analysis of road accidents that occur on or alongside the road lines network in the BMR.\n\nBefore we go into the analysis, we visualise the geospatial data (to save bandwidth, we directly use plot mode):\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode('plot')\ntm_shape(roadacc)+\n  tm_dots(col = \"red\")+\n  tm_shape(roadsbkk)+\n  tm_lines()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01B_files/figure-html/unnamed-chunk-52-1.png){width=672}\n:::\n:::\n\n\n### 10.1 Network KDE (NKDE) Analysis\n\nNKDE is used to visualise and explore the intensity of point processes i.e. road accidents along the network i.e. road lines.\n\n### 10.1.1 Determining appropriate bandwidth\n\nBefore we compute NKDE, we need to select an appropriate bandwidth ([reference](https://cran.r-project.org/web/packages/spNetwork/vignettes/NKDE.html)). In this case we will use the K nearest neighbour adaptive bandwidth. Under this method, the K nearest neighbour distance could be used as a locally adapted bandwidth for intensity estimation.\n\nWe will first use the nearest neighbour distance to understand the distance between road accident points along the road lines in BMR - we do this by running *nndist()* function on our ppp object:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnnd_dist <- nndist(roadacc_owin_ppp.km)\nsummary(nnd_dist)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n0.00000 0.00123 0.01303 0.07336 0.04663 7.73467 \n```\n\n\n:::\n:::\n\n\nThe median and max distance between road lines in BMR is 0.01303 km and 7.73467 km respectively.\n\nWe first aggregate events that are very close i.e. round up of median distance \\~15 metres away:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroadacc$weight <- 1\nroadacc_agg <- aggregate_points(roadacc,15, weight = \"weight\")\n```\n:::\n\n\nWe then calculate for each event its distance to its 20th neighbour:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknn_dists <- network_knn(origins = roadacc_agg,\n                         lines = roadsbkk,\n                         k = 30,\n                         maxdistance = 5000,\n                         line_weight = \"length\",\n                         digits = 2,\n                         tol = 0.1)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbws <- knn_dists$distances[,20]\n\nggplot()+\n  geom_histogram(aes(x=bws),\n                 fill = \"white\",\n                 color = \"black\",\n                 bins = 50)+\n  labs(x = \"distance to 20th neighbour (metres)\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01B_files/figure-html/unnamed-chunk-56-1.png){width=672}\n:::\n:::\n\n\nBased on the histogram above, we note that there are some events for which the 20th neighbour is very far. We decide to trim the bandwidth at 10000 metres.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrimmed_bw <- ifelse(bws > 10000,10000, bws)\n```\n:::\n\n\n### 10.1.2 Preparing the lixels objects\n\nBefore computing NKDE, the *roadsbkk* object needs to be cut into lixels with a specified minimal distance. We do this using [lixelize_lines()](https://jeremygelb.github.io/spNetwork/reference/lixelize_lines.html) of **spNetwork.**\n\nTo determine the appropriate lixel size to use, we need to consider several factors such as the scale of our study, density of accidents. road network characteristics. Some reasons are provided below:\n\n-   [scale of study]{.underline}: shorter lixels may allow capturing of finer details for study of road accidents at a local scale however longer lixels may be more suitable to study patterns over larger distances.\n\n-   [density of accidents]{.underline}: high road accident density areas may benefit from shorter lixels that would enable the capture of precise clustering on small road segments. however, long lixels can help to smooth out analysis for less dense areas and avoid overrepresenting sparsely populated segments\n\n-   [road network characteristics]{.underline}: more complex road networks may benefit from shorter lixels to indicate the finer details of the road lines while larger road networks may work better with longer lixels.\n\nBased on the analysis of K-nearest neighbors with adaptive bandwidth under [10.1.1 Determining appropriate bandwidth], we observe from the histogram that most road accidents occur within 1000m to 2000m of each other. We hence set the lixel lengths within this distance to help capture the density of accidents more effectively:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlixels <- lixelize_lines(roadsbkk,\n                         2000,\n                         mindist = 1000)\nsamples <- lines_center(lixels)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndensities <- nkde(lines = roadsbkk,\n                  events = roadacc_agg,\n                  w = roadacc_agg$weight,\n                  samples = samples,\n                  kernel_name = \"quartic\",\n                  bw = trimmed_bw,\n                  div = \"bw\",\n                  adaptive = FALSE,\n                  method = \"simple\",\n                  digits = 1,\n                  tol = 1,\n                  grid_shape = c(5,5),\n                  verbose = FALSE,\n                  diggle_correction = FALSE,\n                  study_area = NULL,\n                  max_depth = 5,\n                  agg = NULL,\n                  sparse = TRUE)\n```\n:::\n\n\nTo minimise re-running the code above, we save densities generated as a new rds file:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nwrite_rds(densities,\"data/rds/densities.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ndensities <- read_rds(\"data/rds/densities.rds\")\n```\n:::\n\n\n### 10.1.3 Visualising NKDE\n\nBefore visualising NKDE values, we insert the computed density values into *samples* and *lixels* objects as density field. We also multiply the densities by 1000 to rescale the density values from metres (as the EPSG 32647 projection system is in metres which make the computed density values very small and hard to comprehend) to number of events per kilometer. We then map the result:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# rescaling to help the mapping\nsamples$density <- densities*1000\nlixels$density <- densities*1000\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncolorRamp <- brewer.pal(n = 5, name = \"Spectral\")\ncolorRamp <- rev(colorRamp)\n\nsamples2 <- samples[order(samples$density),]\ntitle <- paste0(\"Road accident density by kilometres in BMR,\",\n                \"\\nusing an adaptive bandwidth (20th nearest neighbour)\")\n\ntmap_mode('plot')\ntm_shape(roadsbkk) + \n  tm_lines(\"black\") + \n  tm_shape(samples2) + \n  tm_dots(\"density\", style = \"kmeans\", palette = colorRamp, n = 5, size = 0.1) + \n  tm_layout(legend.outside = TRUE, \n            main.title = title, main.title.size = 1)\n```\n:::\n\n\nPlotting it in the lixel density format:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolorRamp <- brewer.pal(n = 5, name = \"RdYlGn\")\ncolorRamp <- rev(colorRamp)\n\nlix_density_break <- quantile(lixels$density, probs = seq(0, 1, length.out = 5))\ntitle <- paste0(\"Road accident density by kilometres in BMR,\",\n                \"\\nusing an adaptive bandwidth (20th nearest neighbour)\")\n\ntmap_mode('plot')\ntm_shape(lixels) +\n  tm_lines(col = \"density\", palette = colorRamp, breaks = lix_density_break) +\n  tm_shape(roadacc_agg) +\n  tm_dots(col = \"black\", size = 0.01)+\n  tm_layout(legend.outside = TRUE, \n            main.title = title, main.title.size = 1)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01B_files/figure-html/unnamed-chunk-64-1.png){width=672}\n:::\n:::\n\n\nBased on the plot above, we observe the following:\n\n-   Dense occurrence of road accidents within central Bangkok along intricate road networks where there are more complicated road lines\n\n-   Denser occurrence of road accidents at intersections of road segments\n\n## 11. Temporal Network SPPA\n\n### 11.1 Temporal Analysis of Road Accidents by Month\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroadacc$inc_month <- as.numeric(roadacc$inc_month)\nroadacc$inc_dayofweek <- as.numeric(roadacc$inc_dayofweek)\nroadacc$inc_time <- as.numeric(roadacc$inc_time)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nw <- rep(1,nrow(roadacc))\nsamples <- seq(min(roadacc$inc_month),max(roadacc$inc_month),0.5)\n\nmonth_kernel_val <- data.frame(\n  bw_1 = tkde(roadacc$inc_month, w=w, samples = samples, bw = 1, kernel_name = \"quartic\"),\n  bw_2 = tkde(roadacc$inc_month, w=w, samples = samples, bw = 2, kernel_name = \"quartic\"),\n  bw_3 = tkde(roadacc$inc_month, w=w, samples = samples, bw = 3, kernel_name = \"quartic\"),\n  bw_4 = tkde(roadacc$inc_month, w=w, samples = samples, bw = 4, kernel_name = \"quartic\"),\n  bw_5 = tkde(roadacc$inc_month, w=w, samples = samples, bw = 5, kernel_name = \"quartic\"),\n  bw_6 = tkde(roadacc$inc_month, w=w, samples = samples, bw = 6, kernel_name = \"quartic\"),\n  time = samples\n)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmonth_lab <- c(\"Jan\", \"Feb\", \"Mar\", \"Apr\", \"May\", \"Jun\", \"Jul\", \"Aug\", \"Sep\", \"Oct\", \"Nov\", \"Dec\")\n\ndf_month <- reshape2::melt(month_kernel_val, id.vars = \"time\")\n\ndf_month$variable <- as.factor(df_month$variable)\n\nggplot(data = df_month)+\n  geom_line(aes(x=time,y=value))+\n  scale_x_continuous(breaks =1:12, labels = month_lab) +\n  facet_wrap(vars(variable),ncol=2, scales=\"free\")+\n  labs(title = \"Temporal NKDE for Occurrence of Road Accidents by Month\", x = \"Month\", y=\"Density\")+\n  theme(axis.text = element_text(size = 5))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01B_files/figure-html/unnamed-chunk-67-1.png){width=672}\n:::\n:::\n\n\nIt seems that a bandwidth of 3 best captures the bimodal shape of the temporal dimension of road accidents.\n\n### 11.2 Temporal Analysis of Road Accidents by Day of Week\n\n\n::: {.cell}\n\n```{.r .cell-code}\nw <- rep(1,nrow(roadacc))\nsamples <- seq(min(roadacc$inc_dayofweek),max(roadacc$inc_dayofweek),0.5)\n\nday_kernel_val <- data.frame(\n  bw_1 = tkde(roadacc$inc_dayofweek, w=w, samples = samples, bw = 1, kernel_name = \"quartic\"),\n  bw_2 = tkde(roadacc$inc_dayofweek, w=w, samples = samples, bw = 2, kernel_name = \"quartic\"),\n  bw_3 = tkde(roadacc$inc_dayofweek, w=w, samples = samples, bw = 3, kernel_name = \"quartic\"),\n  bw_4 = tkde(roadacc$inc_dayofweek, w=w, samples = samples, bw = 4, kernel_name = \"quartic\"),\n  time = samples\n)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nday_lab <- c(\"Sun\", \"Mon\", \"Tues\", \"Wed\", \"Thu\", \"Fri\", \"Sat\")\n\ndf_day <- reshape2::melt(day_kernel_val, id.vars = \"day\")\ndf_day$variable <- as.factor(df_day$variable)\n\nggplot(data = df_day)+\n  geom_line(aes(x=inc_dayofweek,y=value))+\n  scale_x_continuous(breaks =7, labels = day_lab) +\n  facet_wrap(vars(variable),ncol=2, scales=\"free\")+\n  labs(title = \"Temporal NKDE for Occurrence of Road Accidents by Day of the Week\", x = \"Day\", y=\"Density\")+\n  theme(axis.text = element_text(size = 5))\n```\n:::\n\n\n### Spatial dimension\n\nBefore considering the spatio-temporal case, we can also investigate the spatial dimension.\n",
    "supporting": [
      "Take-home_Ex01B_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}