{
  "hash": "5fd85f9d0092b366925941abef9c911d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home Exercise 2\"\nauthor: \"Kock Si Min\"\ndate: October 2, 2024\ndate-modified: \"last-modified\"\ntoc: true\nexecute:\n  eval: true\n  echo: true\n  freeze: true\n  warning: false\n  message: false\n---\n\n\n# Take-home Exercise 2: Discovering impacts of COVID-19 on Thailand tourism economy at the province level using spatial and spatio-temporal statistics\n\n## 1. Setting the Scene\n\nTourism is one of Thailand’s largest industries, accounting for \\~20% of the gross domestic product (GDP). In 2019, Thailand earned US\\$90 billion from domestic and international tourism, but the COVID-19 pandemic caused revenues to crash to US\\$24 billion in 2020.\n\nThe figure below shows the total revenue receipt from tourism sector between Jan 2019 to Feb 2023, and indicates that the revenue from tourism industry has been gradually recovering since Sep 2021.\n\n![](images/clipboard-378385426.png){width=\"460\"}\n\nHowever, it is important to note that the tourism economy of Thailand is not evenly distributed. The figure below reveals that the tourism economy of Thailand in 2019 was mainly focused on five provinces, namely Bangkok, Phuket, Chon Buri, Krabi and Chiang Mai.\n\n## 2. Objectives\n\nThe objectives of this take-home exercise will be to discover:\n\n-   if the key indicators of tourism economy of Thailand are independent from space and space and time.\n\n-   If the tourism economy is indeed spatial and spatio-temporal dependent, and if so, where the clusters, outliers and emerging hot spot/cold spot areas are.\n\n## 3. The Task\n\nThe specific tasks of this take-home exercise are as follows:\n\n-   Using appropriate function of **sf** and **tidyverse**, prepare the following geospatial data layer:\n\n    -   a study area layer in sf polygon features. It must be at [province level](https://en.wikipedia.org/wiki/Provinces_of_Thailand) (including Bangkok) of Thailand.\n\n    -   a tourism economy indicators layer within the study area in sf polygon features.\n\n    -   a derived tourism economy indicator layer in [**spacetime s3 class of sfdep**](https://sfdep.josiahparry.com/articles/spacetime-s3). Keep the time series at **month and year levels**.\n\n-   Using the extracted data, perform global spatial autocorrelation analysis using [sfdep methods](https://is415-gaa-tskam.netlify.app/in-class_ex/in-class_ex05/in-class_ex05-glsa).\n\n-   Using the extracted data, perform local spatial autocorrelation analysis using [sfdep methods](https://r4gdsa.netlify.app/chap10.html).\n\n-   Using the extracted data, perform emerging hotspot analysis using [sfdep methods](https://is415-gaa-tskam.netlify.app/in-class_ex/in-class_ex05/in-class_ex05-ehsa).\n\n-   Describe the spatial patterns revealed by the analysis above.\n\n## 4. Installing and Loading the necessary R packages\n\nWe use the following code chunk to install and load the necessary R packages for our analysis:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, sfdep, tmap, tidyverse, knitr, plotly, Kendall, VIM, naniar, DT)\n```\n:::\n\n\n## 5. The Data\n\nTwo data sets shall be used:\n\n-   [Thailand Domestic Tourism Statistics](https://www.kaggle.com/datasets/thaweewatboy/thailand-domestic-tourism-statistics) at Kaggle - **version 2** of the data set will be used.\n\n-   [Thailand - Subnational Administrative Boundaries](https://data.humdata.org/dataset/cod-ab-tha?) at HDX - the province boundary data set will be used.\n\n### 5.1 Thailand Domestic Tourism Statistics\n\n### 5.1.1 Importing the csv file\n\nThe code chunk below uses [`read_csv()`](https://readr.tidyverse.org/reference/read_delim.html) of readr package to load the Thailand Domestic Tourism Statistics:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntourism <- read_csv(\"data/rawdata/thailand_domestic_tourism_2019_2023_ver2.csv\")\n```\n:::\n\n\nThe *thai_tourism* data has 30,800 rows and 7 variables, namely *date, province_thai, province_eng, region_thai, region_eng, variable* and *value.*\n\n### 5.1.2 Cleaning the data\n\n#### 5.1.2.1 Dropping unwanted variables\n\nWe will drop the columns *province_thai* and *region_thai* as these variables are in the Thai language which we do not understand and hence will not be helpful for our analysis:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntourism <- tourism[,!names(tourism) %in% c(\"province_thai\",\"region_thai\")]\n```\n:::\n\n\n#### 5.1.2.2 Determine the presence of missing data\n\nWe determine the presence of missing values using the *vis_miss()* function of the [naniar](https://cran.r-project.org/web/packages/naniar/vignettes/getting-started-w-naniar.html) package:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvis_miss(tourism)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nFrom the output above, we note that there are no missing data.\n\n#### 5.1.2.3 Creating new year, month and day variables\n\nFrom the code chunk below, we note that the *date* variable in *tourism* data frame is in the Date vector format:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(tourism$date)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Date\"\n```\n\n\n:::\n:::\n\n\nWe form new variables *year* and *month* using the lubridate package:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntourism <- tourism %>%\n  mutate(year_month = ymd(date),\n         year = year(date),\n         month = month(date,\n                       label = TRUE,\n                       abbr = TRUE),\n.before = 2)\n```\n:::\n\n\n#### 5.1.2.4 Determine the distribution of provinces and corresponding regions\n\nWe first study the distribution of regions in the data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(tourism, \n       aes(x = fct_reorder(region_eng, region_eng, .fun = length))) + \n  geom_bar() +\n  labs(title = \"Distribution of domestic tourism statistics across regions\", x = \"Regions\", y = \"Count\") +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nFrom the output above, we note that there 5 different types of regions represented, notably the western region is not represented in the data.\n\nWe take a more detailed look by determining the unique provinces represented in the data and their corresponding regions. This step aims to check for two things:\n\n-   whether there are any duplicate data entries i.e. entries that are meant to represent the same province but have spelling errors.\n\n-   whether the regions for the provinces are accurately indicated\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntourism_unique <- tourism %>%\n  select(province_eng,region_eng) %>%\n  distinct() %>%\n  arrange(region_eng,province_eng)\n\ntourism_unique\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 77 × 2\n   province_eng             region_eng\n   <chr>                    <chr>     \n 1 Ang Thong                central   \n 2 Bangkok                  central   \n 3 Chainat                  central   \n 4 Kanchanaburi             central   \n 5 Lopburi                  central   \n 6 Nakhon Pathom            central   \n 7 Nonthaburi               central   \n 8 Pathum Thani             central   \n 9 Phetchaburi              central   \n10 Phra Nakhon Si Ayutthaya central   \n# ℹ 67 more rows\n```\n\n\n:::\n:::\n\n\nFrom the output above, we note that all 77 Thailand provinces are represented in the data, and that there are no spelling errors/misrepresented provinces.\n\nHowever, with reference to the [source on provinces in Thailand](https://en.wikipedia.org/wiki/Provinces_of_Thailand), we note a few mistakes in the regions indicated for the provinces.\n\n-   Kanchanaburi, Phetchaburi, Prachuap Khiri Khan and Ratchaburi are stated as being in the central region but actually reside in the west region\n\n-   Nakhon Nayok is stated as being in the east region but actually resides in the central region\n\n-   The *east_northeast* region can actually be renamed as *northeast* region for clarity and consistency with how detailed the other provinces are labelled\n\n-   Kamphaeng Phet, Nakhon Sawan, Phetchabun, Phichit, Phitsanulok, Sukhothai and Uthai Thani are stated as being in the north region but actually reside in central region\n\n-   Tak is stated as being in the north region but actually resides in the west region\n\n-   Sisaket is stated as being in the south region but actually resides in the northeast region\n\n#### 5.1.2.4.1 Correcting the erroneous regions of provinces\n\nWe use the code chunk below to rename the \"east_northeast\" region to just \"northeast\" and correct the erroneous regions of the provinces mentioned above:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntourism <- tourism %>%\n  mutate(region_eng = case_when(\n    region_eng == \"east_northeast\" ~ \"northeast\",\n    province_eng %in% c(\"Kanchanaburi\", \"Phetchaburi\", \"Prachuap Khiri Khan\", \"Ratchaburi\", \"Tak\") ~ \"west\",\n    province_eng %in% c(\"Nakhon Nayok\",\"Kamphaeng Phet\",\"Nakhon Sawan\",\"Phetchabun\",\"Phichit\",\"Phitsanulok\",\"Sukhothai\",\"Uthai Thani\") ~ \"central\",\n    province_eng == \"Sisaket\" ~ \"northeast\",\n    TRUE ~ region_eng\n  ))\n```\n:::\n\n\nWe check by generating the data table of provinces and their corresponding regions:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntourism_unique <- tourism %>%\n  select(province_eng,region_eng) %>%\n  distinct() %>%\n  arrange(region_eng,province_eng)\n\ndatatable(tourism_unique)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-49f5296fd558357deb15\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-49f5296fd558357deb15\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\",\"27\",\"28\",\"29\",\"30\",\"31\",\"32\",\"33\",\"34\",\"35\",\"36\",\"37\",\"38\",\"39\",\"40\",\"41\",\"42\",\"43\",\"44\",\"45\",\"46\",\"47\",\"48\",\"49\",\"50\",\"51\",\"52\",\"53\",\"54\",\"55\",\"56\",\"57\",\"58\",\"59\",\"60\",\"61\",\"62\",\"63\",\"64\",\"65\",\"66\",\"67\",\"68\",\"69\",\"70\",\"71\",\"72\",\"73\",\"74\",\"75\",\"76\",\"77\"],[\"Ang Thong\",\"Bangkok\",\"Chainat\",\"Kamphaeng Phet\",\"Lopburi\",\"Nakhon Nayok\",\"Nakhon Pathom\",\"Nakhon Sawan\",\"Nonthaburi\",\"Pathum Thani\",\"Phetchabun\",\"Phichit\",\"Phitsanulok\",\"Phra Nakhon Si Ayutthaya\",\"Samut Prakan\",\"Samut Sakhon\",\"Samut Songkhram\",\"Saraburi\",\"Sing Buri\",\"Sukhothai\",\"Suphan Buri\",\"Uthai Thani\",\"Chachoengsao\",\"Chanthaburi\",\"Chonburi\",\"Prachinburi\",\"Rayong\",\"Sa Kaeo\",\"Trat\",\"Chiang Mai\",\"Chiang Rai\",\"Lampang\",\"Lamphun\",\"Mae Hong Son\",\"Nan\",\"Phayao\",\"Phrae\",\"Uttaradit\",\"Amnat Charoen\",\"Bueng Kan\",\"Buriram\",\"Chaiyaphum\",\"Kalasin\",\"Khon Kaen\",\"Loei\",\"Maha Sarakham\",\"Mukdahan\",\"Nakhon Phanom\",\"Nakhon Ratchasima\",\"Nong Bua Lamphu\",\"Nong Khai\",\"Roi Et\",\"Sakon Nakhon\",\"Sisaket\",\"Surin\",\"Ubon Ratchathani\",\"Udon Thani\",\"Yasothon\",\"Chumphon\",\"Krabi\",\"Nakhon Si Thammarat\",\"Narathiwat\",\"Pattani\",\"Phang Nga\",\"Phatthalung\",\"Phuket\",\"Ranong\",\"Satun\",\"Songkhla\",\"Surat Thani\",\"Trang\",\"Yala\",\"Kanchanaburi\",\"Phetchaburi\",\"Prachuap Khiri Khan\",\"Ratchaburi\",\"Tak\"],[\"central\",\"central\",\"central\",\"central\",\"central\",\"central\",\"central\",\"central\",\"central\",\"central\",\"central\",\"central\",\"central\",\"central\",\"central\",\"central\",\"central\",\"central\",\"central\",\"central\",\"central\",\"central\",\"east\",\"east\",\"east\",\"east\",\"east\",\"east\",\"east\",\"north\",\"north\",\"north\",\"north\",\"north\",\"north\",\"north\",\"north\",\"north\",\"northeast\",\"northeast\",\"northeast\",\"northeast\",\"northeast\",\"northeast\",\"northeast\",\"northeast\",\"northeast\",\"northeast\",\"northeast\",\"northeast\",\"northeast\",\"northeast\",\"northeast\",\"northeast\",\"northeast\",\"northeast\",\"northeast\",\"northeast\",\"south\",\"south\",\"south\",\"south\",\"south\",\"south\",\"south\",\"south\",\"south\",\"south\",\"south\",\"south\",\"south\",\"south\",\"west\",\"west\",\"west\",\"west\",\"west\"]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>province_eng<\\/th>\\n      <th>region_eng<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"columnDefs\":[{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"province_eng\",\"targets\":1},{\"name\":\"region_eng\",\"targets\":2}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\nRe-plotting the distribution of domestic tourism statistics across the regions:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(tourism, \n       aes(x = fct_reorder(region_eng, region_eng, .fun = length))) + \n  geom_bar(fill = \"skyblue\") +\n  labs(title = \"Distribution of domestic tourism statistics across regions\", x = \"Regions\", y = \"Count\") +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nWe note that most of the domestic tourism statistics come from the central region, followed by northeast, south, north, east and finally the west region.\n\n#### 5.1.2.5 Determine the distribution of variables and corresponding values\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(tourism, \n       aes(x = fct_reorder(variable, variable, .fun = length))) + \n  geom_bar(fill = \"skyblue\") +\n  labs(title = \"Distribution of Variable\", x = \"Variable\", y = \"Count\") +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nWe note that there are 8 different types of variables:\n\n| S/N   | Variable           | Definition                                                                  |\n|-------------|-------------|----------------------------------------------|\n| **1** | no_tourist_all     | The total number of domestic tourists who visited the province              |\n| **2** | no_tourist_thai    | The number of Thai tourists who visited the province                        |\n| **3** | no_tourist_foreign | The number of foreign tourists who visited the province                     |\n| **4** | no_tourist_stay    | The total number of tourists who stay overnight                             |\n| **5** | ratio_tourist_stay | Ratio of tourists that stay overnight                                       |\n| **6** | revenue_all        | The revenue generated by the tourism industry in the province, in Thai Baht |\n| **7** | revenue_foreign    | The revenue generated by foreign tourists in the province, in Thai Baht     |\n| **8** | revenue_thai       | The revenue generated by Thai tourists in the province, in Thai Baht        |\n\n#### 5.1.2.5.1 pivot_wider() to expand variables as individual columns\n\nWe utilise the *pivot_wider()* function to separate the different variable types as individual columns:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntourism_wider <- tourism %>%\n  pivot_wider(names_from = variable, values_from = value)\n```\n:::\n\n\n#### 5.1.2.5.2 Checking the revenue figures\n\nBased on the definition of the different variable types, we note that \"revenue_all\" should equal to the sum of \"revenue_foreign\" and \"revenue_thai\". We check through the data using the code chunk below:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrevenue_numbers <- tourism_wider %>%\n  group_by(province_eng,year_month) %>%\n  summarise(\n    sum_revenue = sum(revenue_foreign, revenue_thai, na.rm = TRUE),\n  revenue_all = sum(revenue_all,na.rm = TRUE),\n            .groups = \"drop\") %>%\n  mutate(is_rev_equal = sum_revenue == revenue_all)\n\nrevenue_numbers\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3,850 × 5\n   province_eng  year_month sum_revenue revenue_all is_rev_equal\n   <chr>         <date>           <dbl>       <dbl> <lgl>       \n 1 Amnat Charoen 2019-01-01    34510000    34510000 TRUE        \n 2 Amnat Charoen 2019-02-01    32290000    32290000 TRUE        \n 3 Amnat Charoen 2019-03-01    39070000    39070000 TRUE        \n 4 Amnat Charoen 2019-04-01    32040000    32040000 TRUE        \n 5 Amnat Charoen 2019-05-01    30110000    30110000 TRUE        \n 6 Amnat Charoen 2019-06-01    26630000    26630000 TRUE        \n 7 Amnat Charoen 2019-07-01    21680000    21680000 TRUE        \n 8 Amnat Charoen 2019-08-01    17700000    17700000 TRUE        \n 9 Amnat Charoen 2019-09-01    19500000    19500000 TRUE        \n10 Amnat Charoen 2019-10-01    61440000    61440000 TRUE        \n# ℹ 3,840 more rows\n```\n\n\n:::\n:::\n\n\nWe note from the output below that the data entries for revenue match up:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrevenue_numbers %>%\n  filter(!is_rev_equal)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 0 × 5\n# ℹ 5 variables: province_eng <chr>, year_month <date>, sum_revenue <dbl>,\n#   revenue_all <dbl>, is_rev_equal <lgl>\n```\n\n\n:::\n:::\n\n\n#### 5.1.2.5.3 Checking the tourist numbers\n\nSimilarly, based on the definition of the different variable types, we note that \"no_tourist_all\" should equal to the sum of \"no_tourist_foreign\" and \"no_tourist_thai\". We check through the data using the code chunk below:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntourism_numbers <- tourism_wider %>%\n  group_by(province_eng,year_month) %>%\n  summarise(\n    sum_tourists = sum(no_tourist_foreign, no_tourist_thai, na.rm = TRUE),\n  tourists_all = sum(no_tourist_all,na.rm = TRUE),\n            .groups = \"drop\") %>%\n  mutate(is_touristno_equal = sum_tourists == tourists_all)\n\ntourism_numbers\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3,850 × 5\n   province_eng  year_month sum_tourists tourists_all is_touristno_equal\n   <chr>         <date>            <dbl>        <dbl> <lgl>             \n 1 Amnat Charoen 2019-01-01        21790        21790 TRUE              \n 2 Amnat Charoen 2019-02-01        20377        20377 TRUE              \n 3 Amnat Charoen 2019-03-01        24786        24786 TRUE              \n 4 Amnat Charoen 2019-04-01        23792        23792 TRUE              \n 5 Amnat Charoen 2019-05-01        22436        22436 TRUE              \n 6 Amnat Charoen 2019-06-01        19714        19714 TRUE              \n 7 Amnat Charoen 2019-07-01        20517        20517 TRUE              \n 8 Amnat Charoen 2019-08-01        16708        16708 TRUE              \n 9 Amnat Charoen 2019-09-01        18453        18453 TRUE              \n10 Amnat Charoen 2019-10-01        39242        39242 TRUE              \n# ℹ 3,840 more rows\n```\n\n\n:::\n:::\n\n\nWe note from the output below that the data entries for tourist numbers match up:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntourism_numbers %>%\n  filter(!is_touristno_equal)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 0 × 5\n# ℹ 5 variables: province_eng <chr>, year_month <date>, sum_tourists <dbl>,\n#   tourists_all <dbl>, is_touristno_equal <lgl>\n```\n\n\n:::\n:::\n\n\n#### 5.1.2.5.4 Checking the distribution of values of each variable\n\n-   Revenue\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselected_revenue <- tourism %>%\n  filter(variable %in% c(\"revenue_all\", \"revenue_thai\", \"revenue_foreign\"))\n\n# Calculate summary statistics\nsummary_stats <- selected_revenue %>%\n  group_by(variable) %>%\n  summarise(\n    Min = min(value),\n    Q1 = quantile(value, 0.25),\n    Median = median(value),\n    Q3 = quantile(value, 0.75),\n    Max = max(value)\n  )\n\nggplot(selected_revenue, aes(x = variable, y = value, fill = variable)) +\n  geom_boxplot() +\n  geom_text(data=summary_stats, aes(x = variable, \n                               y = Max + 1000, \n                               label = paste(\"Min:\", Min,\n                                             \"\\nQ1:\", Q1, \n                                             \"\\nMedian:\", Median, \n                                             \"\\nQ3:\", Q3, \n                                             \"\\nMax:\", Max)),\n            position = position_dodge(width = 0.75), \n            vjust = 0, hjust = 1, size = 2, color = \"black\") +\n  labs(title = \"Boxplots of Different Revenue Types\", x = \"Revenue Type\", y = \"Revenue\")+\n  scale_y_continuous(limits = c(0,12e+10))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\nFrom the boxplots above, we note that the minimum value for \"revenue_foreign\" is -\\$4250, while this could have occurred due to errors in data entry, we note that it could also be due to negative tourism impacts i.e. refunds and cancellations as the negative foreign revenues occurred in Jul and Aug 2021 in Nakhon Pathom, coinciding with the time period when [Thailand announced a new 14-day COVID-19 restriction in Bangkok and surrounding provinces including Nakhon Pathom](https://www.tatnews.org/2021/07/thailand-announces-new-14-day-covid-19-restrictions-in-bangkok-and-5-surrounding-provinces/). As such, these entries were not removed from the data.\n\n-   Tourist numbers\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselected_tourists <- tourism %>%\n  filter(variable %in% c(\"no_tourist_all\",\"no_tourist_thai\", \"no_tourist_foreign\"))\n\n# Calculate summary statistics\nsummary_stats <- selected_tourists %>%\n  group_by(variable) %>%\n  summarise(\n    Min = min(value),\n    Q1 = quantile(value, 0.25),\n    Median = median(value),\n    Q3 = quantile(value, 0.75),\n    Max = max(value)\n  )\n\nggplot(selected_tourists, aes(x = variable, y = value, fill = variable)) +\n  geom_boxplot() +\n  geom_text(data=summary_stats, aes(x = variable, \n                               y = Max + 100000, \n                               label = paste(\"Min:\", Min,\n                                             \"\\nQ1:\", Q1, \n                                             \"\\nMedian:\", Median, \n                                             \"\\nQ3:\", Q3, \n                                             \"\\nMax:\", Max)),\n            position = position_dodge(width = 0.75), \n            vjust = 0, hjust = 1, size = 2, color = \"black\") +\n  labs(title = \"Boxplots of Different Tourist Numbers\", x = \"Tourist Type\", y = \"Number of Tourists\")+\n  scale_y_continuous(limits = c(0,8e+6))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n-   Occupancy\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate summary statistics\nsummary_stats <- tourism_wider %>%\n  summarise(\n    Min = min(no_tourist_stay),\n    Q1 = quantile(no_tourist_stay, 0.25),\n    Median = median(no_tourist_stay),\n    Q3 = quantile(no_tourist_stay, 0.75),\n    Max = max(no_tourist_stay)\n  )\n\nggplot(tourism_wider, aes(x = \"\", y = no_tourist_stay)) +\n  geom_boxplot(fill = \"lightblue\") +\n  geom_text(data = summary_stats, aes(x = \"\", y = Max + 100000,\n                                      label = paste(\"Min:\", Min,\n                                                     \"\\nQ1:\", Q1,\n                                                     \"\\nMedian:\", Median,\n                                                     \"\\nQ3:\", Q3,\n                                                     \"\\nMax:\", Max)),\n            vjust = 0, size = 2, color = \"black\") +\n  labs(title = \"Distribution of Number of Hotel Rooms Occupied\",\n       y = \"Number of Occupied Hotel Rooms\") +\n  scale_y_continuous(limits = c(0,4e+6))+\n  theme(axis.title.x = element_blank())\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n#### 5.1.2.5.5 Removing *date* variable\n\nWe remove the \"date\" variable to keep the data more tidy for further analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntourism <- tourism_wider %>%\n  select(-date)\n```\n:::\n\n\n#### 5.1.2.6 Saving as a new rds file\n\nWe save the cleaned data as a new rds file:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntourism_cleaned <- write_rds(tourism,\"data/rds/tourism_cleaned.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntourism_cleaned <- read_rds(\"data/rds/tourism_cleaned.rds\")\n```\n:::\n\n::: {.cell}\n\n:::\n\n\n### 5.1.3 Creating a data frame for spatial analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntourism_cleaned_spat <- tourism_cleaned %>%\n  group_by(province_eng, region_eng) %>%\n  summarize(median_tot_revenue = median(revenue_all, na.rm = TRUE),\n            median_foreign_revenue = median(revenue_foreign, na.rm = TRUE),\n            median_thai_revenue = median(revenue_thai, na.rm = TRUE),\n            median_tot_tourist = median(no_tourist_all, na.rm = TRUE),\n            median_tot_foreign = median(no_tourist_foreign, na.rm = TRUE),\n            median_tot_thai = median(no_tourist_thai, na.rm = TRUE),\n            median_occup_rate = median(ratio_tourist_stay, na.rm = TRUE),\n            median_occup_no = median(no_tourist_stay, na.rm = TRUE),\n            .groups = 'drop')\n```\n:::\n\n\n#### 5.1.3.1 Saving as a new rds file\n\nWe save the file as a new rds file:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntourism_cleaned_spat <- write_rds(tourism_cleaned_spat,\"data/rds/tourism_cleaned_spat.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntourism_cleaned_spat <- read_rds(\"data/rds/tourism_cleaned_spat.rds\")\n```\n:::\n\n\n### 5.1.4 Creating a data frame for temporal analysis\n\nWe plot the total revenue by year_month:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntourism_cleaned_summary <- tourism_cleaned %>%\n  mutate(year_month = as.character(year_month)) %>%\n  group_by(year_month) %>%\n  summarize(total_revenue = sum(revenue_all, na.rm = TRUE))\n\nggplot(tourism_cleaned_summary, aes(x = year_month, y = total_revenue)) +\n  geom_bar(stat = \"identity\", fill = \"skyblue\") +\n  labs(title = \"Total Revenue by Year-Month\", x = \"Year-Month\", y = \"Total Revenue\") +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\nBased on the distribution of total revenue across the year_month variable, it can be seen that temporally, we can split the data into 3 time periods, namely:\n\n-   pre-COVID: Between Jan 2019 to Mar 2020\n\n-   during COVID: Between Apr 2020 to Aug 2021\n\n-   post-COVID: Between Sep 2021 to Feb 2023\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntourism_cleaned_temp <- tourism_cleaned %>%\n  mutate(time_period = case_when(\n    year_month >= \"2019-01-01\" & year_month <= \"2020-03-01\" ~ \"Pre-COVID\",\n    year_month >= \"2020-04-01\" & year_month <= \"2021-08-01\" ~ \"During-COVID\",\n    year_month >= \"2021-09-01\" & year_month <= \"2023-02-01\" ~ \"Post-COVID\",\n    TRUE ~ NA_character_))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntourism_cleaned_temp <- tourism_cleaned_temp %>%\n  group_by(province_eng,time_period) %>%\n  summarize(median_tot_revenue = median(revenue_all, na.rm = TRUE),\n            median_foreign_revenue = median(revenue_foreign, na.rm = TRUE),\n            median_thai_revenue = median(revenue_thai, na.rm = TRUE),\n            median_tot_tourist = median(no_tourist_all, na.rm = TRUE),\n            median_tot_foreign = median(no_tourist_foreign, na.rm = TRUE),\n            median_tot_thai = median(no_tourist_thai, na.rm = TRUE),\n            median_occup_rate = median(ratio_tourist_stay, na.rm = TRUE),\n            median_occup_no = median(no_tourist_stay, na.rm = TRUE),\n            .groups = 'drop')\n```\n:::\n\n\n#### 5.1.4.1 Saving as a new rds file\n\nWe save the file as a new rds file:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntourism_cleaned_temp <- write_rds(tourism_cleaned_temp,\"data/rds/tourism_cleaned_temp.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntourism_cleaned_temp <- read_rds(\"data/rds/tourism_cleaned_temp.rds\")\n```\n:::\n\n\n### 5.2 Thailand Subnational Administrative Boundaries\n\n### 5.2.1 Importing the shapefile\n\nThe code chunk below uses `st_read()` of **sf** package to import the Thailand Subnational Administrative Boundaries shapefile into R. There are a few different files representing different levels of administrative boundaries - level 0 (country), level 1 (province), level 2 (district) and level 3 (sub-district, tambon). As we are only interested in province level administrative boundaries, we will just load the file corresponding to level 1.\n\nThe imported shapefile will be a **simple features** **object** of **sf**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprovince <- st_read(dsn = \"data/rawdata\",\n                    layer = \"tha_admbnda_adm1_rtsd_20220121\")\n```\n:::\n\n\nWe note that the simple features data has a multipolygon geometry and has 77 features and 16 fields. It is in WGS84 geographic coordinate system.\n\n### 5.2.2 Removing the unwanted variables\n\nOf the fields available, only \"ADM1_EN\" and \"geometry\" are essential hence the following code chunk keeps only these two variables in the simple features object:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprovince <- province %>%\n  select(ADM1_EN)\n```\n:::\n\n\n### 5.2.3 Checking the name of the provinces\n\nAs we will be joining the *province* simple features object and the attribute data from *tourism_cleaned* using the province names (ADM1_EN in *province* simple features object and province_eng in *tourism_cleaned* dataframe), it is important to check through the naming of the provinces to ensure that they all match up.\n\nWe extract the unique province names from both *tourism_cleaned* and *province:*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunique_tour_prov <- tourism_cleaned %>%\n  distinct(province_eng)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nunique_shp_prov <- province %>%\n  distinct(ADM1_EN)\n```\n:::\n\n\nWe then combine via a full join and read through the list of province names for discrepancies:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncombined_prov <- full_join(unique_shp_prov,unique_tour_prov,\n                           by = c(\"ADM1_EN\"=\"province_eng\"))\n```\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncombined_prov <- combined_prov %>%\n  arrange(ADM1_EN)\n\ncombined_prov\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    ADM1_EN\n1             Amnat Charoen\n2                 Ang Thong\n3                   Bangkok\n4                 Bueng Kan\n5                  Buri Ram\n6                   Buriram\n7              Chachoengsao\n8                  Chai Nat\n9                   Chainat\n10               Chaiyaphum\n11              Chanthaburi\n12               Chiang Mai\n13               Chiang Rai\n14                Chon Buri\n15                 Chonburi\n16                 Chumphon\n17                  Kalasin\n18           Kamphaeng Phet\n19             Kanchanaburi\n20                Khon Kaen\n21                    Krabi\n22                  Lampang\n23                  Lamphun\n24                     Loei\n25                 Lop Buri\n26                  Lopburi\n27             Mae Hong Son\n28            Maha Sarakham\n29                 Mukdahan\n30             Nakhon Nayok\n31            Nakhon Pathom\n32            Nakhon Phanom\n33        Nakhon Ratchasima\n34             Nakhon Sawan\n35      Nakhon Si Thammarat\n36                      Nan\n37               Narathiwat\n38         Nong Bua Lam Phu\n39          Nong Bua Lamphu\n40                Nong Khai\n41               Nonthaburi\n42             Pathum Thani\n43                  Pattani\n44                Phang Nga\n45                 Phangnga\n46              Phatthalung\n47                   Phayao\n48               Phetchabun\n49              Phetchaburi\n50                  Phichit\n51              Phitsanulok\n52 Phra Nakhon Si Ayutthaya\n53                    Phrae\n54                   Phuket\n55             Prachin Buri\n56              Prachinburi\n57      Prachuap Khiri Khan\n58                   Ranong\n59               Ratchaburi\n60                   Rayong\n61                   Roi Et\n62                  Sa Kaeo\n63             Sakon Nakhon\n64             Samut Prakan\n65             Samut Sakhon\n66          Samut Songkhram\n67                 Saraburi\n68                    Satun\n69                Si Sa Ket\n70                Sing Buri\n71                  Sisaket\n72                 Songkhla\n73                Sukhothai\n74              Suphan Buri\n75              Surat Thani\n76                    Surin\n77                      Tak\n78                    Trang\n79                     Trat\n80         Ubon Ratchathani\n81               Udon Thani\n82              Uthai Thani\n83                Uttaradit\n84                     Yala\n85                 Yasothon\n```\n\n\n:::\n:::\n\n\nWe note repeated entries for eight provinces which are spelt differently in the original *province* sf object vs *tourism_cleaned* dataframe:\n\n-   Buri Ram vs Buriram\n\n-   Chai Nat vs Chainat\n\n-   Chon Buri vs Chonburi\n\n-   Lop Buri vs Lopburi\n\n-   Nong Bua Lam Phu vs Nong Bua Lamphu\n\n-   Phangnga vs Phang Nga\n\n-   Prachin Buri vs Prachinburi\n\n-   Si Sa Ket vs Sisaket\n\n#### 5.2.3.1 Adjusting the naming of provinces in *province* sf object\n\nWe utilise the following code chunk to adjust the naming of the eight provinces to be aligned with the naming in the *tourism_cleaned* dataframe to faciliate relational join in subsequent analysis. We also rename \"ADM1_EN\" to \"province_eng\" to faciliate the creation of timeseries cube in subsequent analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprovince <- province %>%\n  mutate(ADM1_EN = case_when(\n    ADM1_EN == \"Buri Ram\" ~ \"Buriram\",\n    ADM1_EN == \"Chai Nat\" ~ \"Chainat\",\n    ADM1_EN == \"Chon Buri\" ~ \"Chonburi\",\n    ADM1_EN == \"Lop Buri\" ~ \"Lopburi\",\n    ADM1_EN == \"Nong Bua Lam Phu\" ~ \"Nong Bua Lamphu\",\n    ADM1_EN == \"Phangnga\" ~ \"Phang Nga\",\n    ADM1_EN == \"Prachin Buri\" ~ \"Prachinburi\",\n    ADM1_EN == \"Si Sa Ket\" ~ \"Sisaket\",\n    TRUE ~ ADM1_EN)) %>%\n  rename(province_eng = ADM1_EN)\n```\n:::\n\n\nWe save this as new rds file to avoid reloading the original datafile above:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprovince <- write_rds(province,\"data/rds/province.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nprovince <- read_rds(\"data/rds/province.rds\")\n```\n:::\n\n\n### 5.3 Performing relational join\n\n### 5.3.1 Relational join with *tourism_cleaned* data frame\n\nWe then perform a left relational join to update the *province* sf object with the attribute fields of the *tourism_cleaned* data frame:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncombined_prov_tourism <- left_join(province,tourism_cleaned)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(combined_prov_tourism)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 3,850\nColumns: 14\n$ province_eng       <chr> \"Bangkok\", \"Bangkok\", \"Bangkok\", \"Bangkok\", \"Bangko…\n$ year_month         <date> 2019-01-01, 2020-01-01, 2021-01-01, 2022-01-01, 20…\n$ year               <dbl> 2019, 2020, 2021, 2022, 2023, 2019, 2020, 2021, 202…\n$ month              <ord> Jan, Jan, Jan, Jan, Jan, Feb, Feb, Feb, Feb, Feb, M…\n$ region_eng         <chr> \"central\", \"central\", \"central\", \"central\", \"centra…\n$ ratio_tourist_stay <dbl> 93.37, 89.36, 7.54, 26.34, 75.02, 89.19, 68.37, 9.9…\n$ no_tourist_stay    <dbl> 3334971, 3213765, 354676, 1009583, 2440463, 3025538…\n$ no_tourist_all     <dbl> 5959075, 6046765, 1681847, 2437497, 4872078, 521140…\n$ no_tourist_thai    <dbl> 3534061, 3573040, 1632693, 2299906, 2749877, 291992…\n$ no_tourist_foreign <dbl> 2425014, 2473725, 49154, 137591, 2122201, 2291482, …\n$ revenue_all        <dbl> 81926490000, 88202890000, 9539730000, 11823610000, …\n$ revenue_thai       <dbl> 29742580000, 31137650000, 8447450000, 9642600000, 1…\n$ revenue_foreign    <dbl> 52183910000, 57065240000, 1092280000, 2181010000, 4…\n$ geometry           <MULTIPOLYGON [°]> MULTIPOLYGON (((100.6139 13..., MULTIP…\n```\n\n\n:::\n:::\n\n\nWe note that the *combined_prov_tourism* data has the same number of rows, 3848 rows, as the original *tourism_cleaned* data frame indicating that the cleaning up of the different province spellings was done accurately.\n\n#### 5.3.1.1 Saving as a new rds file\n\nWe save the combined file as a new rds file and load it into the R environment for further analysis:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncombined_data <- write_rds(combined_prov_tourism,\"data/rds/combined_prov_tourism.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncombined_data <- read_rds(\"data/rds/combined_prov_tourism.rds\")\n```\n:::\n\n\n### 5.3.2 Relational join with *tourism_cleaned_spat* data frame\n\nWe also perform a left relational join to update the *province* sf object with the attribute fields of the *tourism_cleaned_spat* data frame:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncombined_tourism_spat <- left_join(province,tourism_cleaned_spat)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(combined_tourism_spat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 77\nColumns: 11\n$ province_eng           <chr> \"Bangkok\", \"Samut Prakan\", \"Nonthaburi\", \"Pathu…\n$ region_eng             <chr> \"central\", \"central\", \"central\", \"central\", \"ce…\n$ median_tot_revenue     <dbl> 16554390000, 228515000, 216067500, 135655000, 8…\n$ median_foreign_revenue <dbl> 8025340000, 26780000, 4880000, 1740000, 1550500…\n$ median_thai_revenue    <dbl> 11973495000, 194440000, 214815000, 129105000, 7…\n$ median_tot_tourist     <dbl> 2681686.0, 149277.0, 161057.5, 100804.0, 557916…\n$ median_tot_foreign     <dbl> 308839.5, 19441.5, 2029.0, 1166.5, 8347.5, 7.0,…\n$ median_tot_thai        <dbl> 2309799.5, 127042.5, 157859.5, 98375.5, 495576.…\n$ median_occup_rate      <dbl> 35.355, 28.300, 37.590, 25.980, 48.660, 28.995,…\n$ median_occup_no        <dbl> 1151894.5, 47140.5, 54486.0, 23215.0, 68597.0, …\n$ geometry               <MULTIPOLYGON [°]> MULTIPOLYGON (((100.6139 13..., MU…\n```\n\n\n:::\n:::\n\n\n#### 5.3.2.1 Saving as a new rds file\n\nWe save the combined file as a new rds file and load it into the R environment for further analysis:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncombined_data_spat <- write_rds(combined_tourism_spat,\"data/rds/combined_data_spat.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncombined_data_spat <- read_rds(\"data/rds/combined_data_spat.rds\")\n```\n:::\n\n\n### 5.3.3 Relational join with *tourism_cleaned_temp* data frame\n\nWe also perform a left relational join to update the *province* sf object with the attribute fields of the *tourism_cleaned_temp* data frame:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncombined_tourism_temp <- left_join(province,tourism_cleaned_temp)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(combined_tourism_temp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 231\nColumns: 11\n$ province_eng           <chr> \"Bangkok\", \"Bangkok\", \"Bangkok\", \"Samut Prakan\"…\n$ time_period            <chr> \"During-COVID\", \"Post-COVID\", \"Pre-COVID\", \"Dur…\n$ median_tot_revenue     <dbl> 9539730000, 22927845000, 87753820000, 64680000,…\n$ median_foreign_revenue <dbl> 1152230000, 11714170000, 54153040000, 50000, 46…\n$ median_thai_revenue    <dbl> 8348660000, 11762345000, 29052570000, 64680000,…\n$ median_tot_tourist     <dbl> 1115611.0, 2879758.0, 5620260.0, 51035.0, 16007…\n$ median_tot_foreign     <dbl> 53676.0, 613626.0, 2087831.0, 61.0, 36441.0, 83…\n$ median_tot_thai        <dbl> 1063854.0, 2363948.0, 3534061.0, 51035.0, 12833…\n$ median_occup_rate      <dbl> 11.270, 41.065, 79.440, 7.740, 29.115, 57.790, …\n$ median_occup_no        <dbl> 476161.0, 1246119.5, 3008999.0, 9972.0, 47503.5…\n$ geometry               <MULTIPOLYGON [°]> MULTIPOLYGON (((100.6139 13..., MU…\n```\n\n\n:::\n:::\n\n\n#### 5.3.3.1 Saving as a new rds file\n\nWe save the combined file as a new rds file and load it into the R environment for further analysis:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncombined_data_temp <- write_rds(combined_tourism_temp,\"data/rds/combined_data_temp.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncombined_data_temp <- read_rds(\"data/rds/combined_data_temp.rds\")\n```\n:::\n\n\n### 5.4 Creating a time series cube\n\nWe will use [spacetime()](https://sfdep.josiahparry.com/articles/spacetime-s3.html) of sfdep to create a spatio-temporal cube. However before that we will convert the date field into integer format.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspt <- tourism_cleaned %>%\n  mutate(year_month = as.integer(gsub(\"-\",\"\",year_month)))\n```\n:::\n\n\nThe following code chunk is then used to create a spatio-temporal cube:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspt <- spacetime(\n  spt,\n  province,\n  .loc_col = \"province_eng\",\n  .time_col = \"year_month\"\n)\n```\n:::\n\n\n### 5.4.1 Verifying space-time cube object\n\nWe utilise the following code chunk to verify if *spt* is indeed a space-time cube object:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nis_spacetime_cube(spt)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n### 5.4.2 Saving as a new rds file\n\nWe save *spt* as a new rds file and load it into the R environment for further analysis:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspt <- write_rds(spt,\"data/rds/spt.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nspt <- read_rds(\"data/rds/spt.rds\")\n```\n:::\n\n\n## 6. Key Indicators of the Tourism Economy of Thailand\n\nFrom the above data, we note that there are several possible key indicators of the tourism economy of Thailand to analyse, namely: (i) Total revenue, (ii) Revenue generated from foreign tourists, (iii) Revenue generated from local/Thai tourists, (iv) Total number of tourists, (v) Number of foreign tourists, (vi) Number of local/Thai tourists and (vii) Rate of tourists who stay overnight. For our analysis, we will focus on the following indicators for reasons stated below:\n\n\\(i\\) **Total revenue:** Revenue generated from both foreign and local tourists can indicate how well Thai's tourism economy is performing.\n\n\\(ii\\) **Number of foreign tourists:** Based on [literature](https://www.adb.org/sites/default/files/linked-documents/54177-001-sd-12.pdf), Thailand recorded a total THB1.9 trillion receipts from foreign tourists (65% of the sector’s receipts) or 11.5% of its GDP in 2019. The daily foreign tourist spending was around \\$192 per person, more than double of domestic tourists spending. The number of foreign tourists will hence be a strong indicator of how well the Thai tourism economy is performing i.e. the greater number of tourists, coupled with their higher propensity to spend, would be indicative of a booming tourism economy.\n\n\\(iii\\) **Rate of tourists who stay overnight:** A higher rate of tourists who stay overnight can be indicative of how well the tourism economy is performing as tourists who stay for longer periods in Thailand are likely to incur more expenditure i.e. via spending on accommodation, more activities.\n\n### 6.1 Visualising Indicators of Tourism Economy\n\nWe briefly visualise the distribution of these indicators:\n\n::: panel-tabset\n## Total Revenue\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\ntm_shape(combined_data_spat)+\n  tm_fill(\"median_tot_revenue\",\n          style = \"quantile\",\n          title = \"Median Total Revenue\")+\n  tm_borders(alpha = 0.5)+\n  tm_layout(main.title = \"Distribution of Median Total Revenue (Quantile classification)\",main.title.position = \"center\",\n            main.title.size = 0.5,\n            legend.height = 0.45,\n            legend.width = 0.35,\n            legend.text.size = 0.5,\n            legend.outside.size = 0.5)+\n  tm_text(\"province_eng\",size = 0.3)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-61-1.png){width=672}\n:::\n:::\n\n\n## Number of Foreign Tourists\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\ntm_shape(combined_data_spat)+\n  tm_fill(\"median_tot_foreign\",\n          style = \"quantile\",\n          title = \"Median Number of Foreign Tourists\")+\n  tm_borders(alpha = 0.5)+\n  tm_layout(main.title = \"Distribution of Median Number of Foreign Tourists (Quantile classification)\",main.title.position = \"center\",\n            main.title.size = 0.5,\n            legend.height = 0.45,\n            legend.width = 0.35,\n            legend.text.size = 0.5,\n            legend.outside.size = 0.5)+\n  tm_text(\"province_eng\",size = 0.3)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-62-1.png){width=672}\n:::\n:::\n\n\n## Rate of tourists who stay overnight\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\ntm_shape(combined_data_spat)+\n  tm_fill(\"median_occup_rate\",\n          style = \"quantile\",\n          title = \"Median Rate of Overnights Tourists\")+\n  tm_borders(alpha = 0.5)+\n  tm_layout(main.title = \"Distribution of Median Rate of Overnights Tourists (Quantile classification)\",main.title.position = \"center\",\n            main.title.size = 0.5,\n            legend.height = 0.45,\n            legend.width = 0.35,\n            legend.text.size = 0.5,\n            legend.outside.size = 0.5)+\n  tm_text(\"province_eng\",size = 0.3)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-63-1.png){width=672}\n:::\n:::\n\n:::\n\n## 7. Determining independence from space\n\n### 7.1 Computing Distance-based Spatial Weights\n\nThere are two main ways of computing spatial weights - contiguity spatial weights or distance-based spatial weights. Based on the plot of the provinces of Thailand, we note that it would not be appropriate to utilise contiguity spatial weights as there would be provinces with too little neighbours. We will hence utilise distance-based spatial weights.\n\n### 7.1.1 Generating centroids\n\nA connectivity graph takes a point and displays a line to each neighbouring point. As we are working with multipolygons, we will need to get points to make connectivity graphs. As such, we will need to calculate centroids for each province.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncentroids <- combined_data_spat %>%\n  st_centroid() %>%  \n  select(province_eng, geometry)\n```\n:::\n\n\n### 7.1.2 Saving as a new rds file\n\nWe save *centroids* as a new rds file and load it into the R environment for further analysis:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncentroids <- write_rds(centroids,\"data/rds/centroids.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncentroids <- read_rds(\"data/rds/centroids.rds\")\n```\n:::\n\n\n### 7.1.3 Visualising the centroids\n\nWe visualise where these centroids are:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode('plot')\ntm_shape(province) +\n  tm_fill()+\n  tm_borders()+\n  tm_shape(centroids)+\n  tm_dots(col = \"darkblue\", size = 0.2, alpha = 0.5, title = \"Centroids\") +\n  tm_text(\"province_eng\", size = 0.5, col = \"black\") +\n  tm_layout(main.title = \"Centroids of Provinces\", main.title.size = 0.5) \n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-67-1.png){width=672}\n:::\n:::\n\n\nWe note that none of the centroids generated are in the water and are all located within the regions of provinces. This indicates that the centroids are appropriate for use and do not need to be shifted.\n\n### 7.1.4 Converting centroids to coordinates\n\nWe convert the centroids to coordinates using the following code chunk to facilitate further analysis:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoords <- st_coordinates(centroids)\n```\n:::\n\n\n### 7.1.5 Computing adaptive distance weight matrix\n\nGiven that the polygons differ in size, we will utilise adaptive distance weight matrix.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknn6 <- st_knn(coords,k=6)\nknn6\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 77 \nNumber of nonzero links: 462 \nPercentage nonzero weights: 7.792208 \nAverage number of links: 6 \nNon-symmetric neighbours list\n```\n\n\n:::\n:::\n\n\nWe display the content of the matrix using the code chunk below:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(knn6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 77\n $ : int [1:6] 2 3 4 5 59 60\n $ : int [1:6] 1 3 4 11 59 60\n $ : int [1:6] 1 2 4 5 59 60\n $ : int [1:6] 1 2 3 5 17 59\n $ : int [1:6] 1 3 4 6 8 10\n $ : int [1:6] 4 5 8 9 10 58\n $ : int [1:6] 5 6 8 9 10 17\n $ : int [1:6] 5 6 7 9 10 58\n $ : int [1:6] 6 7 8 48 49 58\n $ : int [1:6] 4 5 6 7 8 17\n $ : int [1:6] 1 2 12 13 15 16\n $ : int [1:6] 2 11 13 14 15 16\n $ : int [1:6] 11 12 14 15 16 18\n $ : int [1:6] 11 12 13 15 16 18\n $ : int [1:6] 1 2 11 12 16 17\n $ : int [1:6] 4 10 11 15 17 18\n $ : int [1:6] 1 4 5 10 15 16\n $ : int [1:6] 13 15 16 17 19 20\n $ : int [1:6] 10 16 17 18 20 25\n $ : int [1:6] 18 19 21 22 33 34\n $ : int [1:6] 20 22 24 26 33 34\n $ : int [1:6] 20 21 23 24 26 34\n $ : int [1:6] 21 22 24 26 34 38\n $ : int [1:6] 22 23 26 34 35 38\n $ : int [1:6] 7 19 28 29 33 55\n $ : int [1:6] 22 23 24 34 35 38\n $ : int [1:6] 28 30 32 35 36 37\n $ : int [1:6] 25 29 30 31 32 35\n $ : int [1:6] 25 28 30 33 34 35\n $ : int [1:6] 27 28 29 32 35 36\n $ : int [1:6] 28 30 32 42 53 55\n $ : int [1:6] 27 28 30 31 35 36\n $ : int [1:6] 20 21 24 29 34 35\n $ : int [1:6] 21 24 26 33 35 38\n $ : int [1:6] 24 29 33 34 36 38\n $ : int [1:6] 27 30 32 35 37 38\n $ : int [1:6] 24 26 27 35 36 38\n $ : int [1:6] 24 26 34 35 36 37\n $ : int [1:6] 40 41 43 45 46 47\n $ : int [1:6] 39 41 43 47 51 52\n $ : int [1:6] 39 40 42 43 45 52\n $ : int [1:6] 31 41 43 44 52 53\n $ : int [1:6] 40 41 42 44 45 52\n $ : int [1:6] 31 41 42 43 45 46\n $ : int [1:6] 39 41 42 43 44 46\n $ : int [1:6] 39 40 41 43 44 45\n $ : int [1:6] 39 40 41 43 45 46\n $ : int [1:6] 7 8 9 49 50 54\n $ : int [1:6] 8 9 48 50 57 58\n $ : int [1:6] 48 49 51 52 53 54\n $ : int [1:6] 40 48 49 50 52 54\n $ : int [1:6] 41 42 43 50 51 53\n $ : int [1:6] 31 42 50 52 54 55\n $ : int [1:6] 9 48 50 52 53 55\n $ : int [1:6] 7 25 31 48 53 54\n $ : int [1:6] 1 3 59 60 61 62\n $ : int [1:6] 6 9 49 56 58 59\n $ : int [1:6] 5 6 8 9 57 59\n $ : int [1:6] 1 3 4 5 60 61\n $ : int [1:6] 1 2 3 56 59 61\n $ : int [1:6] 1 3 56 59 60 62\n $ : int [1:6] 3 56 59 60 61 63\n $ : int [1:6] 2 56 60 61 62 70\n $ : int [1:6] 65 66 67 68 73 74\n $ : int [1:6] 64 66 67 68 73 74\n $ : int [1:6] 64 65 67 68 69 73\n $ : int [1:6] 64 65 66 68 73 74\n $ : int [1:6] 64 65 66 67 69 70\n $ : int [1:6] 64 65 66 67 68 70\n $ : int [1:6] 63 64 65 66 68 69\n $ : int [1:6] 72 73 74 75 76 77\n $ : int [1:6] 64 71 73 74 75 76\n $ : int [1:6] 64 65 67 71 72 74\n $ : int [1:6] 64 65 71 72 73 75\n $ : int [1:6] 71 72 73 74 76 77\n $ : int [1:6] 71 72 73 74 75 77\n $ : int [1:6] 71 72 73 74 75 76\n - attr(*, \"region.id\")= chr [1:77] \"1\" \"2\" \"3\" \"4\" ...\n - attr(*, \"call\")= language spdep::knearneigh(x = pnts, k = k)\n - attr(*, \"sym\")= logi FALSE\n - attr(*, \"type\")= chr \"knn\"\n - attr(*, \"knn-k\")= num 6\n - attr(*, \"class\")= chr [1:2] \"nb\" \"list\"\n```\n\n\n:::\n:::\n\n\nBased on the output from above, we note that each province has six neighbours.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweights <- st_weights(knn6)\n```\n:::\n\n\n### 7.1.6 Plotting distance-based neighbours\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(combined_data_spat$geometry,border=\"lightgrey\")\nplot(knn6,coords,pch = 19, cex = 0.6, add = TRUE, col = \"red\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-72-1.png){width=672}\n:::\n:::\n\n\n### 7.2 Global Measures of Spatial Autocorrelation\n\n### 7.2.1 Moran's I\n\nMoran's I describe how features differ from the values in the study area as a whole.\n\nH0 null hypothesis: There is no spatial autocorrelation in the indicator of tourism i.e. observed values are spatially randomly distributed and spatial location of the values have no influence on their similarity\n\nH1 alternative hypothesis: There is spatial autocorrelation in the indicator of interest.\n\nWe set the confidence interval to be at 95%.\n\n::: panel-tabset\n## Total Revenue\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nmoran_result <- global_moran_perm(combined_data_spat$median_tot_revenue,\n                                  knn6,\n                                  weights,\n                                  nsim = 1999)\nmoran_result\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 2000 \n\nstatistic = -0.00086168, observed rank = 1385, p-value = 0.615\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n\nWe run a histogram of the results to determine if sufficient simulations have been run i.e. if the distribution of results seem to be close to a normal distribution. Based on the output below, nsim = 1999 seems to be sufficient.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(moran_result$res,\n     freq = TRUE,\n     breaks = 20,\n     xlab = \"Simulated Moran's I\")\n\nabline(v=0,\n       col=\"red\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-74-1.png){width=672}\n:::\n:::\n\n\nBased on the results above, we note that the p-value is 0.615, higher than the p-value of 0.05. This indicates that the p-value is not significant. There is insufficient evidence to reject the null hypothesis at the 95% confidence level.\n\nFurther, the Moran’s I value is close to zero and negative, which indicates that total revenue seem to occur randomly across provinces.\n\n## Number of foreign tourists\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nmoran_result <- global_moran_perm(combined_data_spat$median_tot_foreign,\n                                  knn6,\n                                  weights,\n                                  nsim = 1999)\nmoran_result\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 2000 \n\nstatistic = 0.025733, observed rank = 1780, p-value = 0.22\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(moran_result$res,\n     freq = TRUE,\n     breaks = 20,\n     xlab = \"Simulated Moran's I\")\n\nabline(v=0,\n       col=\"red\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-76-1.png){width=672}\n:::\n:::\n\n\nBased on the results above, we note that the p-value is 0.22, higher than the p-value of 0.05. This indicates that the p-value is not significant. There is insufficient evidence to reject the null hypothesis at the 95% confidence level.\n\nFurther, the Moran’s I value is positive but close to zero, which indicates that number of foreign tourists seem to occur randomly across provinces.\n\n## Rate of tourists who stay overnight\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nmoran_result <- global_moran_perm(combined_data_spat$median_occup_rate,\n                                  knn6,\n                                  weights,\n                                  nsim = 1999)\nmoran_result\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 2000 \n\nstatistic = 0.14629, observed rank = 1978, p-value = 0.022\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(moran_result$res,\n     freq = TRUE,\n     breaks = 20,\n     xlab = \"Simulated Moran's I\")\n\nabline(v=0,\n       col=\"red\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-78-1.png){width=672}\n:::\n:::\n\n\nBased on the results above, we note that the p-value is 0.022, smaller than the p-value of 0.05. This indicates that the p-value is significant. There is sufficient evidence to reject the null hypothesis at the 95% confidence level.\n\nFurther, the Moran’s I value is positive (0.14629) which indicates that the indicator (rate of tourists who stay overnight) has a moderate degree of positive spatial autocorrelation, that it is not randomly distributed across provinces and that nearby provinces are likely to have similar values.\n:::\n\n### 7.2.2 Geary's c\n\nSimilar to Moran's I, Geary's c is also a measure of spatial autocorrelation however it focuses more on the differences between immediate neigbours.\n\nH0 null hypothesis: There is no spatial autocorrelation in the indicator of tourism i.e. observed values are spatially randomly distributed and spatial location of the values have no influence on their dissimilarity\n\nH1 alternative hypothesis: There is spatial autocorrelation in the indicator of interest.\n\nWe set the confidence interval to be at 95%.\n\n::: panel-tabset\n## Total revenue\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\ngeary_result <- global_c_perm(combined_data_spat$median_tot_revenue,\n                                  knn6,\n                                  weights,\n                                  nsim = 1999)\ngeary_result\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Geary C\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 2000 \n\nstatistic = 1.2561, observed rank = 1919, p-value = 0.9595\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n\nWe run a histogram of the results to determine if sufficient simulations have been run i.e. if the distribution of results seem to be close to a normal distribution. Based on the output below, nsim = 1999 seems to be sufficient.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(geary_result$res,\n     freq = TRUE,\n     breaks = 20,\n     xlab = \"Simulated Geary's c\")\n\nabline(v=1,\n       col=\"red\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-80-1.png){width=672}\n:::\n:::\n\n\nBased on the results above, we note that the p-value is 0.9595, higher than the p-value of 0.05. This indicates that the p-value is not significant. There is insufficient evidence to reject the null hypothesis at the 95% confidence level.\n\nLike the result from Moran's I, the Geary's c result also indicates that total revenue seem to occur randomly across provinces.\n\n## Number of foreign tourists\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\ngeary_result <- global_c_perm(combined_data_spat$median_tot_foreign,\n                                  knn6,\n                                  weights,\n                                  nsim = 1999)\ngeary_result\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Geary C\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 2000 \n\nstatistic = 1.2981, observed rank = 1915, p-value = 0.9575\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(geary_result$res,\n     freq = TRUE,\n     breaks = 20,\n     xlab = \"Simulated Geary's c\")\n\nabline(v=1,\n       col=\"red\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-82-1.png){width=672}\n:::\n:::\n\n\nBased on the results above, we note that the p-value is 0.9575, higher than the p-value of 0.05. This indicates that the p-value is not significant. There is insufficient evidence to reject the null hypothesis at the 95% confidence level.\n\nLike the result from Moran's I, the Geary's c result also indicates that number of foreign tourists seem to occur randomly across provinces.\n\n## Rate of tourists who stay overnight\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\ngeary_result <- global_c_perm(combined_data_spat$median_occup_rate,\n                                  knn6,\n                                  weights,\n                                  nsim = 1999)\ngeary_result\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Geary C\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 2000 \n\nstatistic = 0.82128, observed rank = 16, p-value = 0.008\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(geary_result$res,\n     freq = TRUE,\n     breaks = 20,\n     xlab = \"Simulated Geary's c\")\n\nabline(v=1,\n       col=\"red\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-84-1.png){width=672}\n:::\n:::\n\n\nBased on the results above, we note that the p-value is 0.008, smaller than the p-value of 0.05. This indicates that the p-value is significant. There is sufficient evidence to reject the null hypothesis at the 95% confidence level.\n\nFurther, the Geary's c value is slightly less than 1 (0.82128) which indicates that the indicator (rate of tourists who stay overnight) has a moderate degree of positive spatial autocorrelation, that it is not randomly distributed across provinces and that nearby provinces are likely to have similar values. We can hence infer that the spatial distribution of this indicator show signs of clustering. This is a similar finding to the Moran's I result above.\n:::\n\n### 7.3 Local Measures of Spatial Autocorrelation\n\nWe also carry out local measures of spatial autocorrelation. In contrast with global measures of spatial autocorrelation which assesses the overall study area, local measures help to evaluate the spatial distribution of indicators of specific locations with respect to their neighbours and allows the detection of clusters (high-high or low-low) or outliers (high-low or low-high).\n\n### 7.3.1 Total Revenue\n\n::: panel-tabset\n## Local Moran's I\n\nH0 null hypothesis: There is no local spatial autocorrelation in the indicator of tourism i.e. observed values are spatially randomly distributed and there is no relationship between the value at a location and the values at neighbouring locations.\n\nH1 alternative hypothesis: There is local spatial autocorrelation in the indicator of interest. The value at a location is either similar or dissimilar to values at neighbouring locations.\n\nWe set the confidence interval to be at 95%.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234) \nlisa <- combined_data_spat %>%\n  mutate(local_moran = local_moran(combined_data_spat$median_tot_revenue,\n                                 knn6,\n                                 weights,     \n                                 nsim = 1999),\n         .before = 1) %>%\n  unnest(local_moran)\n```\n:::\n\n\nWe visualise local Moran's I and corresponding p-value using the code chunk below:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\nmap1 <- tm_shape(lisa)+\n  tm_fill(\"ii\",\n          title = \"Local Moran Statistic\")+\n  tm_text(\"province_eng\",size = 0.3)+\n  tm_borders(alpha = 0.5)+\n  tm_view(set.zoom.limits = c(6,8))+\n  tm_layout(\n    main.title = \"local Moran's I for Total Revenue\",\n    main.title.size = 0.5\n  )\n\nmap2 <- tm_shape(lisa)+\n  tm_fill(\"p_ii_sim\",\n          breaks = c(0,0.001,0.01,0.05,1),\n          labels = c(\"0.001\",\"0.01\",\"0.05\",\"Not sig\"),\n                     title = \"p-values (based on simulation)\")+\n  tm_text(\"province_eng\",size = 0.3)+\n  tm_borders(alpha = 0.5)+\n  tm_view(set.zoom.limits = c(6,8))+\n  tm_layout(\n    main.title = \"p-value of local Moran's I for Total Revenue\",\n    main.title.size = 0.5\n  )\n\ntmap_arrange(map1, map2, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-86-1.png){width=672}\n:::\n:::\n\n\nBased on the results above, we note that Bangkok displays the strongest negative spatial autocorrelation for total revenue which indicates that it is dissimilar and hence could be an outlier in comparison to its neighbours. However, we note from the corresponding plot of p-values that the p-value for this result is not significant, there is insufficient evidence to reject the null hypothesis at the confidence interval of 95% and indicates that the spatial autocorrelation could have occurred randomly.\n\nOf these provinces, Nakhon Sawan and provinces on the northeast side of Thailand have local moran's I values that are positive but less than 1 with corresponding p-values that are significant. There is hence sufficient evidence to reject the null hypothesis for these provinces. There is local spatial autocorrelation in these provinces and that there is spatial clustering of similar values of total revenue.\n\nIn contrast, the Chachoengsao province has a local moran's I value that is close to 1 but negative and a corresponding significant p-value. There is hence sufficient evidence to reject the null hypothesis for this province. There is local spatial autocorrelation in this province and there is spatial dispersion as the province has a total revenue value dissimilar to its neighbours.\n\n## LISA\n\nWe can also plot the LISA map. In lisa sf data.frame, there are three fields containing the LISA categories - *mean*, *median* and *pysal*. In general, classification in *mean* will be used, as shown in the code chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa_sig <- lisa  %>%\n  filter(p_ii_sim < 0.05)\ntmap_mode(\"plot\")\ntm_shape(lisa) +\n  tm_polygons() +\n  tm_borders(alpha = 0.5) +\ntm_shape(lisa_sig) +\n  tm_fill(\"mean\") + \n  tm_borders(alpha = 0.4)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-87-1.png){width=672}\n:::\n:::\n\n\nSimilar to our interpretation of the local moran's I and p-value plot above, we note that Nakhon Sawan and provinces on the northeast side of Thailand are categorised as Low-Low clusters while Chachoengsao is a Low-High outlier.\n:::\n\n### 7.3.2 Number of foreign tourists\n\n::: panel-tabset\n## Local Moran's I\n\nH0 null hypothesis: There is no local spatial autocorrelation in the indicator of tourism i.e. observed values are spatially randomly distributed and there is no relationship between the value at a location and the values at neighbouring locations.\n\nH1 alternative hypothesis: There is local spatial autocorrelation in the indicator of interest. The value at a location is either similar or dissimilar to values at neighbouring locations.\n\nWe set the confidence interval to be at 95%.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234) \nlisa <- combined_data_spat %>%\n  mutate(local_moran = local_moran(combined_data_spat$median_tot_foreign,\n                                 knn6,\n                                 weights,     \n                                 nsim = 1999),\n         .before = 1) %>%\n  unnest(local_moran)\n```\n:::\n\n\nWe visualise local Moran's I and corresponding p-value using the code chunk below:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\nmap1 <- tm_shape(lisa)+\n  tm_fill(\"ii\",\n          title = \"Local Moran Statistic\")+\n  tm_text(\"province_eng\",size = 0.3)+\n  tm_borders(alpha = 0.5)+\n  tm_view(set.zoom.limits = c(6,8))+\n  tm_layout(\n    main.title = \"local Moran's I for Number of Foreign Tourists\",\n    main.title.size = 0.5\n  )\n\nmap2 <- tm_shape(lisa)+\n  tm_fill(\"p_ii_sim\",\n          breaks = c(0,0.001,0.01,0.05,1),\n          labels = c(\"0.001\",\"0.01\",\"0.05\",\"Not sig\"),\n                     title = \"p-values (based on simulation)\")+\n  tm_text(\"province_eng\",size = 0.3)+\n  tm_borders(alpha = 0.5)+\n  tm_view(set.zoom.limits = c(6,8))+\n  tm_layout(\n    main.title = \"p-value of local Moran's I for Number of Foreign Tourists\",\n    main.title.size = 0.5\n  )\n\ntmap_arrange(map1, map2, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-89-1.png){width=672}\n:::\n:::\n\n\nBased on the results above, we note that Bangkok displays the strongest negative spatial autocorrelation for number of foreign tourists which indicates that it is dissimilar and hence could be an outlier in comparison to its neighbours. Conversely, we note that Chonburi displays the strongest positive spatial autocorrelation for number of foreign tourists which indicates clustering. However, we note from the corresponding plot of p-values that the p-values for these results are not significant, there is insufficient evidence to reject the null hypothesis at the confidence interval of 95% and indicates that the spatial autocorrelation at these two provinces could have occurred randomly.\n\nWe note that provinces Kanchanaburi, Nakhon Sawan, Chainat, Surin, Sisaket, Amnat Charoen, Mukdahan and Samut Prakan have local moran's I values that are positive but less than 1 with corresponding p-values that are significant. There is hence sufficient evidence to reject the null hypothesis for these provinces. There is local spatial autocorrelation in these provinces and that there is spatial clustering of similar values of number of foreign tourists.\n\nIn contrast, the Chachoengsao province has a local moran's I value that are close to 1 but negative and a corresponding significant p-value. There is hence sufficient evidence to reject the null hypothesis for this province. There is local spatial autocorrelation, specifically spatial dispersion as Chachoengsao has a dissimilar number of foreign tourists as compared to its neighbours.\n\n## LISA\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa_sig <- lisa  %>%\n  filter(p_ii_sim < 0.05)\ntmap_mode(\"plot\")\ntm_shape(lisa) +\n  tm_polygons() +\n  tm_borders(alpha = 0.5) +\ntm_shape(lisa_sig) +\n  tm_fill(\"mean\") + \n  tm_borders(alpha = 0.4)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-90-1.png){width=672}\n:::\n:::\n\n\nSimilar to our interpretation of the local moran's I and p-value plot above, we note that there is spatial clustering observed in the following provinces:\n\n-   Kanchanaburi, Nakhon Sawan, Chainat, Surin, Sisaket, Amnat Charoen and Mukdahan are categorised as Low-Low clusters\n\n-   Samut Prakan is categorised as a High-High cluster\n\nConversely, there is spatial disperson for Chachoengsao which has been categorised as a Low-High outlier.\n:::\n\n### 7.3.3 Rate of overnight tourists\n\n::: panel-tabset\n## Local Moran's I\n\nH0 null hypothesis: There is no local spatial autocorrelation in the indicator of tourism i.e. observed values are spatially randomly distributed and there is no relationship between the value at a location and the values at neighbouring locations.\n\nH1 alternative hypothesis: There is local spatial autocorrelation in the indicator of interest. The value at a location is either similar or dissimilar to values at neighbouring locations.\n\nWe set the confidence interval to be at 95%.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234) \nlisa <- combined_data_spat %>%\n  mutate(local_moran = local_moran(combined_data_spat$median_occup_rate,\n                                 knn6,\n                                 weights,     \n                                 nsim = 1999),\n         .before = 1) %>%\n  unnest(local_moran)\n```\n:::\n\n\nWe visualise local Moran's I and corresponding p-value using the code chunk below:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\nmap1 <- tm_shape(lisa)+\n  tm_fill(\"ii\",\n          title = \"Local Moran Statistic\")+\n  tm_text(\"province_eng\",size = 0.3)+\n  tm_borders(alpha = 0.5)+\n  tm_view(set.zoom.limits = c(6,8))+\n  tm_layout(\n    main.title = \"local Moran's I for Rate of Overnight Tourists\",\n    main.title.size = 0.5\n  )\n\nmap2 <- tm_shape(lisa)+\n  tm_fill(\"p_ii_sim\",\n          breaks = c(0,0.001,0.01,0.05,1),\n          labels = c(\"0.001\",\"0.01\",\"0.05\",\"Not sig\"),\n                     title = \"p-values (based on simulation)\")+\n  tm_text(\"province_eng\",size = 0.3)+\n  tm_borders(alpha = 0.5)+\n  tm_view(set.zoom.limits = c(6,8))+\n  tm_layout(\n    main.title = \"p-value of local Moran's I for Rate of Overnight Tourists\",\n    main.title.size = 0.5\n  )\n\ntmap_arrange(map1, map2, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-92-1.png){width=672}\n:::\n:::\n\n\nBased on the results above, we note that the rate of overnight tourist indicator has a more diverse range of local moran's I values as compared to the other two indicators of total revenue and number of foreign tourists.\n\nWe note the following:\n\n-   Phayao, Chiang Rai, Nonthaburi, Ranong, Surat Thani, Bangkok, Phang Nga and Samut Prakan have positive local moran's I values with corresponding significant p-values\n\n-   Mae Hong Son, Nakhon Si Thammarat, Uttaradit and Phra Nakhon Si Ayutthaya have negative local moran's I values with corresponding signficant p-values\n\nThere is hence sufficient evidence to reject the null hypothesis for these provinces. There is local spatial autocorrelation in these provinces - for the former group, there is spatial clustering of similar values of rate of overnight tourists while for the latter, there is spatial dispersion as provinces have dissimilar values of rate of overnight tourists.\n\n## LISA\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa_sig <- lisa  %>%\n  filter(p_ii_sim < 0.05)\ntmap_mode(\"plot\")\ntm_shape(lisa) +\n  tm_polygons() +\n  tm_borders(alpha = 0.5) +\ntm_shape(lisa_sig) +\n  tm_fill(\"mean\") + \n  tm_borders(alpha = 0.4)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-93-1.png){width=672}\n:::\n:::\n\n\nSimilar to our interpretation of the local moran's I and p-value plot above, we note that there is spatial clustering observed in the following provinces:\n\n-   Nonthaburi, Ranong, Surat Thani, Bangkok, Phang Nga and Samut Praka are categorised as Low-Low clusters\n\n-   Phayao and Chiang Rai are categorised as High-High clusters\n\nConversely, there is spatial disperson for Mae Hong Son and Uttaradit which have been categorised as Low-High outliers, and for Nakhon Si Thammarat and Phra Nakhon Si Ayutthaya which have been categorised as High-Low outliers.\n:::\n\n## 8. Determining independence from space and time\n\n## 9. Determining emerging hot spot/cold spot areas\n\n###  9.1 Computing Gi\\*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspt_nb <- spt %>%\n  activate(\"geometry\") %>%\n  mutate(nb = include_self(\n    st_contiguity(geometry)),\n    wt = st_inverse_distance(nb,\n                             geometry,\n                             scale = 1,\n                             alpha = 1),\n    .before = 1) %>%\n  set_nbs(\"nb\") %>%\n  set_wts(\"wt\")\n```\n:::\n\n\nWe then use the new \"nb\" and \"wt\" columns created to calculate the local Gi\\* for each location. We do this by grouping by \"year_month\" and using [local_gstar_perm()](https://sfdep.josiahparry.com/reference/local_gstar) of sfdep package, and thereafter using unnest() to unnest the gi_star column of the newly created *gi_stars* data frame:\n\n::: panel-tabset\n## Total revenue\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngi_stars_totrev <- spt_nb %>%\n  group_by(year_month) %>%\n  mutate(gi_star = local_gstar_perm(\n    revenue_all,\n    nb,\n    wt)) %>%\n  tidyr::unnest(gi_star)\n```\n:::\n\n\n## Number of foreign tourists\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngi_stars_foreign <- spt_nb %>%\n  group_by(year_month) %>%\n  mutate(gi_star = local_gstar_perm(\n    no_tourist_foreign,\n    nb,\n    wt)) %>%\n  tidyr::unnest(gi_star)\n```\n:::\n\n\n## Rate of overnight tourists\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngi_stars_overnight <- spt_nb %>%\n  group_by(year_month) %>%\n  mutate(gi_star = local_gstar_perm(\n    ratio_tourist_stay,\n    nb,\n    wt)) %>%\n  tidyr::unnest(gi_star)\n```\n:::\n\n:::\n\n### 9.2 Mann-Kendall Test\n\nWe then run the Mann-Kendall Test for each location for each indicator:\n\n::: panel-tabset\n## Total revenue\n\n\n::: {.cell}\n\n```{.r .cell-code}\nehsa_totrev <- gi_stars_totrev %>%\n  group_by(province_eng) %>%\n  summarise(mk = list(\n    unclass(\n      Kendall::MannKendall(gi_star)))) %>%\n  tidyr::unnest_wider(mk)\n\nhead(ehsa_totrev)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  province_eng      tau     sl     S     D   varS\n  <chr>           <dbl>  <dbl> <dbl> <dbl>  <dbl>\n1 Amnat Charoen -0.202  0.0396  -247  1225 14292.\n2 Ang Thong      0.0449 0.651     55  1225 14292.\n3 Bangkok       -0.185  0.0587  -227  1225 14292.\n4 Bueng Kan     -0.110  0.262   -135  1225 14292.\n5 Buriram        0.0678 0.493     83  1225 14292.\n6 Chachoengsao  -0.229  0.0192  -281  1225 14292.\n```\n\n\n:::\n:::\n\n\nWe note that not all provinces are statistically significant and that there are a mix of provinces with positive and negative increasing trends.\n\nWe arrange the data to show significant hot/cold spots:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemerging_totrev <- ehsa_totrev %>%\n  arrange(sl,abs(tau)) %>%\n  slice(1:5)\n\nemerging_totrev\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 6\n  province_eng           tau          sl     S     D   varS\n  <chr>                <dbl>       <dbl> <dbl> <dbl>  <dbl>\n1 Trang               -0.517 0.000000125  -633  1225 14292.\n2 Phayao               0.496 0.000000358   607  1225 14292.\n3 Nakhon Si Thammarat -0.489 0.000000567  -599  1225 14292.\n4 Krabi               -0.484 0.000000735  -593  1225 14292.\n5 Surat Thani         -0.484 0.000000735  -593  1225 14292.\n```\n\n\n:::\n:::\n\n\n## Number of foreign tourists\n\n\n::: {.cell}\n\n```{.r .cell-code}\nehsa_foreign <- gi_stars_foreign %>%\n  group_by(province_eng) %>%\n  summarise(mk = list(\n    unclass(\n      Kendall::MannKendall(gi_star)))) %>%\n  tidyr::unnest_wider(mk)\n\nhead(ehsa_foreign)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  province_eng      tau      sl     S     D   varS\n  <chr>           <dbl>   <dbl> <dbl> <dbl>  <dbl>\n1 Amnat Charoen  0.122  0.216     149  1225 14292.\n2 Ang Thong      0.0416 0.676      51  1225 14292.\n3 Bangkok        0.146  0.137     179  1225 14292.\n4 Bueng Kan      0.290  0.00306   355  1225 14292.\n5 Buriram        0.185  0.0587    227  1225 14292.\n6 Chachoengsao  -0.224  0.0219   -275  1225 14292.\n```\n\n\n:::\n:::\n\n\nWe note that not all provinces are statistically significant and that there are a mix of provinces with positive and negative increasing trends.\n\nWe arrange the data to show significant hot/cold spots:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemerging_foreign <- ehsa_foreign %>%\n  arrange(sl,abs(tau)) %>%\n  slice(1:5)\n\nemerging_foreign\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 6\n  province_eng           tau            sl     S     D   varS\n  <chr>                <dbl>         <dbl> <dbl> <dbl>  <dbl>\n1 Trang               -0.576 0.00000000389  -705  1225 14292.\n2 Prachuap Khiri Khan -0.512 0.000000164    -627  1225 14292.\n3 Chanthaburi         -0.378 0.000111       -463  1225 14292.\n4 Nong Khai            0.345 0.000416        423  1225 14292.\n5 Nakhon Si Thammarat -0.344 0.000443       -421  1225 14292.\n```\n\n\n:::\n:::\n\n\n## Rate of overnight tourists\n\n\n::: {.cell}\n\n```{.r .cell-code}\nehsa_overnight <- gi_stars_overnight %>%\n  group_by(province_eng) %>%\n  summarise(mk = list(\n    unclass(\n      Kendall::MannKendall(gi_star)))) %>%\n  tidyr::unnest_wider(mk)\n\nhead(ehsa_overnight)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  province_eng     tau        sl     S     D   varS\n  <chr>          <dbl>     <dbl> <dbl> <dbl>  <dbl>\n1 Amnat Charoen -0.326 0.000871   -399  1225 14292.\n2 Ang Thong     -0.396 0.0000515  -485  1225 14292.\n3 Bangkok       -0.332 0.000683   -407  1225 14292.\n4 Bueng Kan      0.295 0.00260     361  1225 14292.\n5 Buriram        0.430 0.0000108   527  1225 14292.\n6 Chachoengsao  -0.267 0.00639    -327  1225 14292.\n```\n\n\n:::\n:::\n\n\nWe note that not all provinces are statistically significant and that there are a mix of provinces with positive and negative increasing trends.\n\nWe arrange the data to show significant hot/cold spots:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemerging_overnight <- ehsa_overnight %>%\n  arrange(sl,abs(tau)) %>%\n  slice(1:5)\n\nemerging_overnight\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 6\n  province_eng    tau            sl     S     D   varS\n  <chr>         <dbl>         <dbl> <dbl> <dbl>  <dbl>\n1 Phayao        0.564 0               691  1225 14292.\n2 Chainat      -0.566 0.00000000710  -693  1225 14292.\n3 Suphan Buri  -0.553 0.0000000156   -677  1225 14292.\n4 Chiang Rai    0.513 0.000000119     629  1225 14292.\n5 Nan           0.517 0.000000119     633  1225 14292.\n```\n\n\n:::\n:::\n\n:::\n\n### 9.3 Performing emerging hotspot analysis\n\n::: panel-tabset\n## Total revenue\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nehsa_totrev <- emerging_hotspot_analysis(\n  x = spt,\n  .var = \"revenue_all\",\n  k=1,\n  nsim = 99\n)\n\nehsa_totrev\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 77 × 4\n   location                      tau p_value classification     \n   <chr>                       <dbl>   <dbl> <chr>              \n 1 Bangkok                  -0.236   0.0160  sporadic coldspot  \n 2 Samut Prakan              0.00408 0.973   no pattern detected\n 3 Nonthaburi               -0.180   0.0657  sporadic hotspot   \n 4 Pathum Thani             -0.122   0.216   sporadic coldspot  \n 5 Phra Nakhon Si Ayutthaya -0.0873  0.375   no pattern detected\n 6 Ang Thong                -0.238   0.0153  sporadic hotspot   \n 7 Lopburi                  -0.0580  0.558   sporadic coldspot  \n 8 Sing Buri                -0.0351  0.725   no pattern detected\n 9 Chainat                  -0.0498  0.616   no pattern detected\n10 Saraburi                  0.256   0.00906 no pattern detected\n# ℹ 67 more rows\n```\n\n\n:::\n:::\n\n\n### Visualising the distribution of EHSA classes:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(ehsa_totrev,\n       aes(x=classification))+\n  geom_bar()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-105-1.png){width=672}\n:::\n:::\n\n\n### Visualising EHSA:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprov_ehsa_totrev <- province %>%\n  left_join(ehsa_totrev,\n            by = join_by(province_eng == location))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nehsa_totrev_sig <- prov_ehsa_totrev %>%\n  filter(p_value < 0.05)\n\ntmap_mode(\"plot\")\ntm_shape(prov_ehsa_totrev)+\n  tm_polygons()+\n  tm_borders(alpha = 0.5)+\n  tm_shape(ehsa_totrev_sig)+\n  tm_fill(\"classification\")+\n  tm_borders(alpha = 0.4)+\n  tm_text(\"province_eng\",size = 0.5)+\n  tm_layout(\n    main.title = \"Emerging hot/cold spots for Total Revenue\",\n    main.title.size = 0.8,\n    legend.outside = TRUE\n  )\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-107-1.png){width=672}\n:::\n:::\n\n\n## Number of foreign tourists\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nehsa_foreign <- emerging_hotspot_analysis(\n  x = spt,\n  .var = \"no_tourist_foreign\",\n  k=1,\n  nsim = 99\n)\n\nehsa_foreign\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 77 × 4\n   location                     tau   p_value classification     \n   <chr>                      <dbl>     <dbl> <chr>              \n 1 Bangkok                   0.0531 0.592     sporadic coldspot  \n 2 Samut Prakan             -0.202  0.0396    sporadic coldspot  \n 3 Nonthaburi               -0.0792 0.422     sporadic hotspot   \n 4 Pathum Thani              0.200  0.0412    sporadic coldspot  \n 5 Phra Nakhon Si Ayutthaya  0.100  0.307     sporadic coldspot  \n 6 Ang Thong                -0.304  0.00186   sporadic hotspot   \n 7 Lopburi                   0.0759 0.442     sporadic coldspot  \n 8 Sing Buri                 0.100  0.307     sporadic coldspot  \n 9 Chainat                  -0.404  0.0000359 sporadic coldspot  \n10 Saraburi                 -0.0171 0.867     no pattern detected\n# ℹ 67 more rows\n```\n\n\n:::\n:::\n\n\n### Visualising the distribution of EHSA classes:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(ehsa_foreign,\n       aes(x=classification))+\n  geom_bar()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-109-1.png){width=672}\n:::\n:::\n\n\n### Visualising EHSA:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprov_ehsa_foreign <- province %>%\n  left_join(ehsa_foreign,\n            by = join_by(province_eng == location))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nehsa_foreign_sig <- prov_ehsa_foreign %>%\n  filter(p_value < 0.05)\n\ntmap_mode(\"plot\")\ntm_shape(prov_ehsa_foreign)+\n  tm_polygons()+\n  tm_borders(alpha = 0.5)+\n  tm_shape(ehsa_foreign_sig)+\n  tm_fill(\"classification\")+\n  tm_borders(alpha = 0.4)+\n  tm_text(\"province_eng\",size = 0.5)+\n  tm_layout(\n    main.title = \"Emerging hot/cold spots for Number of Tourists\",\n    main.title.size = 0.8,\n    legend.outside = TRUE\n  )\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-111-1.png){width=672}\n:::\n:::\n\n\n## Rate of overnight tourists\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nehsa_overnight <- emerging_hotspot_analysis(\n  x = spt,\n  .var = \"ratio_tourist_stay\",\n  k=1,\n  nsim = 99\n)\n\nehsa_overnight\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 77 × 4\n   location                     tau   p_value classification     \n   <chr>                      <dbl>     <dbl> <chr>              \n 1 Bangkok                  -0.296  0.00246   no pattern detected\n 2 Samut Prakan             -0.318  0.00117   no pattern detected\n 3 Nonthaburi               -0.380  0.000104  no pattern detected\n 4 Pathum Thani              0.198  0.0429    oscilating hotspot \n 5 Phra Nakhon Si Ayutthaya  0.260  0.00781   oscilating hotspot \n 6 Ang Thong                -0.298  0.00233   oscilating coldspot\n 7 Lopburi                  -0.401  0.0000415 no pattern detected\n 8 Sing Buri                 0.0873 0.375     oscilating hotspot \n 9 Chainat                  -0.193  0.0484    no pattern detected\n10 Saraburi                  0.238  0.0153    oscilating hotspot \n# ℹ 67 more rows\n```\n\n\n:::\n:::\n\n\n### Visualising the distribution of EHSA classes:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(ehsa_overnight,\n       aes(x=classification))+\n  geom_bar()\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-113-1.png){width=672}\n:::\n:::\n\n\n### Visualising EHSA:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprov_ehsa_overnight <- province %>%\n  left_join(ehsa_overnight,\n            by = join_by(province_eng == location))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nehsa_overnight_sig <- prov_ehsa_overnight %>%\n  filter(p_value < 0.05)\n\ntmap_mode(\"plot\")\ntm_shape(prov_ehsa_overnight)+\n  tm_polygons()+\n  tm_borders(alpha = 0.5)+\n  tm_shape(ehsa_overnight_sig)+\n  tm_fill(\"classification\")+\n  tm_borders(alpha = 0.4)+\n  tm_text(\"province_eng\",size = 0.5)+\n  tm_layout(\n    main.title = \"Emerging hot/cold spots for Rate of Overnight Tourists\",\n    main.title.size = 0.8,\n    legend.outside = TRUE\n  )\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-115-1.png){width=672}\n:::\n:::\n\n:::\n\n## 10. Conclusion\n\n\\<WIP\\>\n",
    "supporting": [
      "Take-home_Ex02_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<link href=\"../../site_libs/datatables-css-0.0.0/datatables-crosstalk.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/datatables-binding-0.33/datatables.js\"></script>\n<script src=\"../../site_libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\n<link href=\"../../site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css\" rel=\"stylesheet\" />\n<link href=\"../../site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.1/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.1/js/crosstalk.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}